/* AUTO-GENERATED by scripts/gen-preview-css.mjs -- do not edit by hand.
 * Real Tailwind v4 output for Stepper's own classes, compiled against
 * tokens/kortix-tokens.css. Inlined because the preview sandbox runs
 * Tailwind v3 and cannot resolve Suna's v4 @theme tokens. */
export const PREVIEW_CSS = `/*! tailwindcss v4.3.3 | MIT License | https://tailwindcss.com */

  @supports (((-webkit-hyphens: none)) and (not (margin-trim: inline))) or ((-moz-orient: inline) and (not (color: rgb(from red r g b)))) {
    *, :before, :after, ::backdrop {
      --tw-space-y-reverse: 0;
      --tw-border-style: solid;
      --tw-font-weight: initial;
      --tw-shadow: 0 0 #0000;
      --tw-shadow-color: initial;
      --tw-shadow-alpha: 100%;
      --tw-inset-shadow: 0 0 #0000;
      --tw-inset-shadow-color: initial;
      --tw-inset-shadow-alpha: 100%;
      --tw-ring-color: initial;
      --tw-ring-shadow: 0 0 #0000;
      --tw-inset-ring-color: initial;
      --tw-inset-ring-shadow: 0 0 #0000;
      --tw-ring-inset: initial;
      --tw-ring-offset-width: 0px;
      --tw-ring-offset-color: #fff;
      --tw-ring-offset-shadow: 0 0 #0000;
    }
  }



  :root, :host {
    --spacing: .25rem;
    --container-md: 28rem;
    --container-2xl: 42rem;
    --font-weight-medium: 500;
    --default-font-family: var(--font-roobert);
    --default-mono-font-family: var(--font-roobert-mono);
    --color-ring: var(--ring);
  }



  *, :after, :before, ::backdrop {
    box-sizing: border-box;
    border: 0 solid;
    margin: 0;
    padding: 0;
  }

  ::file-selector-button {
    box-sizing: border-box;
    border: 0 solid;
    margin: 0;
    padding: 0;
  }

  html, :host {
    -webkit-text-size-adjust: 100%;
    tab-size: 4;
    line-height: 1.5;
    font-family: var(--default-font-family, -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, "Helvetica Neue", "Noto Sans", Arial, sans-serif, "Apple Color Emoji", "Segoe UI Emoji", "Segoe UI Symbol", "Noto Color Emoji");
    font-feature-settings: var(--default-font-feature-settings, normal);
    font-variation-settings: var(--default-font-variation-settings, normal);
    -webkit-tap-highlight-color: transparent;
  }

  hr {
    height: 0;
    color: inherit;
    border-top-width: 1px;
  }

  abbr:where([title]) {
    -webkit-text-decoration: underline dotted;
    text-decoration: underline dotted;
  }

  h1, h2, h3, h4, h5, h6 {
    font-size: inherit;
    font-weight: inherit;
  }

  a {
    color: inherit;
    -webkit-text-decoration: inherit;
    -webkit-text-decoration: inherit;
    -webkit-text-decoration: inherit;
    text-decoration: inherit;
  }

  b, strong {
    font-weight: bolder;
  }

  code, kbd, samp, pre {
    font-family: var(--default-mono-font-family, ui-monospace, SFMono-Regular, Menlo, Monaco, Consolas, "Liberation Mono", "Courier New", monospace);
    font-feature-settings: var(--default-mono-font-feature-settings, normal);
    font-variation-settings: var(--default-mono-font-variation-settings, normal);
    font-size: 1em;
  }

  small {
    font-size: 80%;
  }

  sub, sup {
    vertical-align: baseline;
    font-size: 75%;
    line-height: 0;
    position: relative;
  }

  sub {
    bottom: -.25em;
  }

  sup {
    top: -.5em;
  }

  table {
    text-indent: 0;
    border-color: inherit;
    border-collapse: collapse;
  }

  :-moz-focusring:where(:not(iframe)) {
    outline: auto;
  }

  progress {
    vertical-align: baseline;
  }

  summary {
    display: list-item;
  }

  ol, ul, menu {
    list-style: none;
  }

  img, svg, video, canvas, audio, iframe, embed, object {
    vertical-align: middle;
    display: block;
  }

  img, video {
    max-width: 100%;
    height: auto;
  }

  button, input, select, optgroup, textarea {
    font: inherit;
    font-feature-settings: inherit;
    font-variation-settings: inherit;
    letter-spacing: inherit;
    color: inherit;
    opacity: 1;
    background-color: #0000;
    border-radius: 0;
  }

  ::file-selector-button {
    font: inherit;
    font-feature-settings: inherit;
    font-variation-settings: inherit;
    letter-spacing: inherit;
    color: inherit;
    opacity: 1;
    background-color: #0000;
    border-radius: 0;
  }

  :where(select:is([multiple], [size])) optgroup {
    font-weight: bolder;
  }

  :where(select:is([multiple], [size])) optgroup option {
    padding-inline-start: 20px;
  }

  ::file-selector-button {
    margin-inline-end: 4px;
  }

  ::placeholder {
    opacity: 1;
  }

  @supports (not ((-webkit-appearance: -apple-pay-button))) or (contain-intrinsic-size: 1px) {
    ::placeholder {
      color: currentColor;
    }

    @supports (color: color-mix(in lab, red, red)) {
      ::placeholder {
        color: color-mix(in oklab, currentcolor 50%, transparent);
      }
    }
  }

  textarea {
    resize: vertical;
  }

  ::-webkit-search-decoration {
    -webkit-appearance: none;
  }

  ::-webkit-date-and-time-value {
    min-height: 1lh;
    text-align: inherit;
  }

  ::-webkit-datetime-edit {
    display: inline-flex;
  }

  ::-webkit-datetime-edit-fields-wrapper {
    padding: 0;
  }

  ::-webkit-datetime-edit {
    padding-block: 0;
  }

  ::-webkit-datetime-edit-year-field {
    padding-block: 0;
  }

  ::-webkit-datetime-edit-month-field {
    padding-block: 0;
  }

  ::-webkit-datetime-edit-day-field {
    padding-block: 0;
  }

  ::-webkit-datetime-edit-hour-field {
    padding-block: 0;
  }

  ::-webkit-datetime-edit-minute-field {
    padding-block: 0;
  }

  ::-webkit-datetime-edit-second-field {
    padding-block: 0;
  }

  ::-webkit-datetime-edit-millisecond-field {
    padding-block: 0;
  }

  ::-webkit-datetime-edit-meridiem-field {
    padding-block: 0;
  }

  ::-webkit-calendar-picker-indicator {
    line-height: 1;
  }

  :-moz-ui-invalid {
    box-shadow: none;
  }

  button, input:where([type="button"], [type="reset"], [type="submit"]) {
    appearance: button;
  }

  ::file-selector-button {
    appearance: button;
  }

  ::-webkit-inner-spin-button {
    height: auto;
  }

  ::-webkit-outer-spin-button {
    height: auto;
  }

  [hidden]:where(:not([hidden="until-found"])) {
    display: none !important;
  }

  :root {
    color-scheme: light;
  }

  .dark {
    color-scheme: dark;
  }





  .relative {
    position: relative;
  }

  .m-0\\.5 {
    margin: calc(var(--spacing) * .5);
  }

  .mt-0\\.5 {
    margin-top: calc(var(--spacing) * .5);
  }

  .mt-1 {
    margin-top: var(--spacing);
  }

  .mt-3 {
    margin-top: calc(var(--spacing) * 3);
  }

  .ml-3 {
    margin-left: calc(var(--spacing) * 3);
  }

  .block {
    display: block;
  }

  .flex {
    display: flex;
  }

  .inline-flex {
    display: inline-flex;
  }

  .size-3 {
    width: calc(var(--spacing) * 3);
    height: calc(var(--spacing) * 3);
  }

  .size-6 {
    width: calc(var(--spacing) * 6);
    height: calc(var(--spacing) * 6);
  }

  .w-full {
    width: 100%;
  }

  .max-w-2xl {
    max-width: var(--container-2xl);
  }

  .max-w-md {
    max-width: var(--container-md);
  }

  .flex-1 {
    flex: 1;
  }

  .shrink-0 {
    flex-shrink: 0;
  }

  .items-center {
    align-items: center;
  }

  .items-start {
    align-items: flex-start;
  }

  .justify-center {
    justify-content: center;
  }

  .gap-2\\.5 {
    gap: calc(var(--spacing) * 2.5);
  }

  .gap-3 {
    gap: calc(var(--spacing) * 3);
  }

  :where(.space-y-4 > :not(:last-child)) {
    --tw-space-y-reverse: 0;
    margin-block-start: calc(calc(var(--spacing) * 4) * var(--tw-space-y-reverse));
    margin-block-end: calc(calc(var(--spacing) * 4) * calc(1 - var(--tw-space-y-reverse)));
  }

  :where(.space-y-6 > :not(:last-child)) {
    --tw-space-y-reverse: 0;
    margin-block-start: calc(calc(var(--spacing) * 6) * var(--tw-space-y-reverse));
    margin-block-end: calc(calc(var(--spacing) * 6) * calc(1 - var(--tw-space-y-reverse)));
  }

  .rounded-full {
    border-radius: 3.40282e38px;
  }

  .rounded-md {
    border-radius: calc(var(--radius) - 2px);
  }

  .border {
    border-style: var(--tw-border-style);
    border-width: 1px;
  }

  .border-border {
    border-color: var(--border);
  }

  .bg-background {
    background-color: var(--background);
  }

  .bg-muted {
    background-color: var(--muted);
  }

  .bg-secondary {
    background-color: var(--secondary);
  }

  .p-4 {
    padding: calc(var(--spacing) * 4);
  }

  .p-6 {
    padding: calc(var(--spacing) * 6);
  }

  .pb-3 {
    padding-bottom: calc(var(--spacing) * 3);
  }

  .text-left {
    text-align: left;
  }

  .font-sans {
    font-family: var(--font-roobert);
  }

  .text-base {
    font-size: 1rem;
    line-height: var(--tw-leading, calc(1.5 / 1));
  }

  .text-sm {
    font-size: .875rem;
    line-height: var(--tw-leading, calc(1.25 / .875));
  }

  .text-xs {
    font-size: .8125rem;
    line-height: var(--tw-leading, calc(1 / .8125));
  }

  .font-medium {
    --tw-font-weight: var(--font-weight-medium);
    font-weight: var(--font-weight-medium);
  }

  .text-foreground {
    color: var(--foreground);
  }

  .text-muted-foreground {
    color: var(--muted-foreground);
  }

  .outline-none {
    --tw-outline-style: none;
    outline-style: none;
  }

  .group-data-\\[orientation\\=horizontal\\]\\/stepper\\:h-0\\.5:is(:where(.group\\/stepper)[data-orientation="horizontal"] *) {
    height: calc(var(--spacing) * .5);
  }

  .group-data-\\[orientation\\=horizontal\\]\\/stepper\\:w-full:is(:where(.group\\/stepper)[data-orientation="horizontal"] *) {
    width: 100%;
  }

  .group-data-\\[orientation\\=horizontal\\]\\/stepper\\:flex-1:is(:where(.group\\/stepper)[data-orientation="horizontal"] *) {
    flex: 1;
  }

  .group-data-\\[orientation\\=horizontal\\]\\/stepper\\:flex-row:is(:where(.group\\/stepper)[data-orientation="horizontal"] *) {
    flex-direction: row;
  }

  .group-data-\\[orientation\\=vertical\\]\\/stepper\\:min-h-4:is(:where(.group\\/stepper)[data-orientation="vertical"] *) {
    min-height: calc(var(--spacing) * 4);
  }

  .group-data-\\[orientation\\=vertical\\]\\/stepper\\:w-0\\.5:is(:where(.group\\/stepper)[data-orientation="vertical"] *) {
    width: calc(var(--spacing) * .5);
  }

  .group-data-\\[orientation\\=vertical\\]\\/stepper\\:flex-1:is(:where(.group\\/stepper)[data-orientation="vertical"] *) {
    flex: 1;
  }

  .group-data-\\[orientation\\=vertical\\]\\/stepper\\:flex-col:is(:where(.group\\/stepper)[data-orientation="vertical"] *) {
    flex-direction: column;
  }

  .group-data-\\[orientation\\=vertical\\]\\/stepper\\:justify-start:is(:where(.group\\/stepper)[data-orientation="vertical"] *) {
    justify-content: flex-start;
  }

  .group-data-\\[orientation\\=vertical\\]\\/stepper\\:self-stretch:is(:where(.group\\/stepper)[data-orientation="vertical"] *) {
    align-self: stretch;
  }

  .group-data-\\[state\\=completed\\]\\/step\\:bg-secondary:is(:where(.group\\/step)[data-state="completed"] *) {
    background-color: var(--secondary);
  }

  .focus-visible\\:z-10:focus-visible {
    z-index: 10;
  }

  .focus-visible\\:border-ring:focus-visible {
    border-color: var(--ring);
  }

  .focus-visible\\:ring-\\[3px\\]:focus-visible {
    --tw-ring-shadow: var(--tw-ring-inset, ) 0 0 0 calc(3px + var(--tw-ring-offset-width)) var(--tw-ring-color, currentcolor);
    box-shadow: var(--tw-inset-shadow), var(--tw-inset-ring-shadow), var(--tw-ring-offset-shadow), var(--tw-ring-shadow), var(--tw-shadow);
  }

  .focus-visible\\:ring-ring\\/50:focus-visible {
    --tw-ring-color: var(--ring);
  }

  @supports (color: color-mix(in lab, red, red)) {
    .focus-visible\\:ring-ring\\/50:focus-visible {
      --tw-ring-color: color-mix(in oklab, var(--ring) 50%, transparent);
    }
  }

  .disabled\\:pointer-events-none:disabled {
    pointer-events: none;
  }

  .disabled\\:opacity-50:disabled {
    opacity: .5;
  }

  .data-\\[orientation\\=horizontal\\]\\:w-full[data-orientation="horizontal"] {
    width: 100%;
  }

  .data-\\[orientation\\=horizontal\\]\\:flex-row[data-orientation="horizontal"] {
    flex-direction: row;
  }

  .data-\\[orientation\\=vertical\\]\\:flex-col[data-orientation="vertical"] {
    flex-direction: column;
  }

  .data-\\[state\\=active\\]\\:bg-secondary[data-state="active"] {
    background-color: var(--secondary);
  }

  .data-\\[state\\=active\\]\\:text-secondary-foreground[data-state="active"] {
    color: var(--secondary-foreground);
  }

  .data-\\[state\\=completed\\]\\:bg-secondary[data-state="completed"] {
    background-color: var(--secondary);
  }

  .data-\\[state\\=completed\\]\\:text-secondary-foreground[data-state="completed"] {
    color: var(--secondary-foreground);
  }


:root {
  --background: oklch(100% 0 0);
  --pane: oklch(100% 0 0);
  --foreground: oklch(0% 0 0);
  --foreground-strong: var(--foreground);
  --foreground-weak: var(--muted-foreground);
  --card: oklch(96.72% 0 0);
  --card-foreground: oklch(0% 0 0);
  --popover: oklch(100% 0 0);
  --popover-foreground: oklch(0% 0 0);
  --primary: oklch(0% 0 0);
  --primary-foreground: oklch(100% 0 0);
  --secondary: oklch(94.31% 0 0);
  --secondary-foreground: oklch(0% 0 0);
  --muted: oklch(94.31% 0 0);
  --muted-foreground: oklch(51.03% 0 0);
  --accent: oklch(96.72% 0 0);
  --accent-foreground: oklch(0% 0 0);
  --destructive: oklch(58.3% .2387 28.4765);
  --destructive-foreground: oklch(98.51% 0 0);
  --border: oklch(91.28% 0 0);
  --input: oklch(94.31% 0 0);
  --ring: oklch(66.9% .1837 248.807);
  --hover: oklch(0% 0 0 / .045);
  --active: oklch(0% 0 0 / .075);
  --focus-ring: var(--ring);
  --chart-1: oklch(87.81% .1688 91.8567);
  --chart-2: oklch(77.24% .1728 65.367);
  --chart-3: oklch(66.71% .1685 53.3814);
  --chart-4: oklch(55.7% .1583 45.3594);
  --chart-5: oklch(47.47% .1358 44.9806);
  --sidebar: oklch(96.72% 0 0);
  --sidebar-foreground: oklch(0% 0 0);
  --sidebar-primary: oklch(66.9% .1837 248.807);
  --sidebar-primary-foreground: oklch(100% 0 0);
  --sidebar-accent: oklch(94.31% 0 0);
  --sidebar-accent-foreground: oklch(0% 0 0);
  --sidebar-border: oklch(91.28% 0 0);
  --sidebar-ring: oklch(66.9% .1837 248.807);
  --radius: .625rem;
  --tracking-normal: 0em;
  --spacing: .23rem;
  --kortix-base: var(--color-ring);
  --kortix-blue: oklch(65.2% .177 252.624);
  --kortix-yellow: oklch(73.2% .15 90.688);
  --kortix-orange: oklch(69.1% .142 71.784);
  --kortix-green: oklch(58.1% .165 146.619);
  --kortix-purple: oklch(67.5% .131 306.212);
  --kortix-red: oklch(64.8% .202 24.745);
  --duration-fast: .1s;
  --duration-normal: .15s;
  --duration-moderate: .2s;
  --duration-slow: .3s;
  --duration-slower: .5s;
  --ease-default: cubic-bezier(.2, 0, 0, 1);
  --ease-in: cubic-bezier(.4, 0, 1, 1);
  --ease-out: cubic-bezier(0, 0, .2, 1);
  --ease-in-out: cubic-bezier(.4, 0, .2, 1);
}

.dark {
  --background: oklch(17% 0 0);
  --pane: oklch(15.43% 0 0);
  --foreground: oklch(100% 0 0);
  --foreground-strong: var(--foreground);
  --foreground-weak: var(--muted-foreground);
  --card: oklch(19.13% 0 0);
  --card-foreground: oklch(100% 0 0);
  --popover: oklch(19.13% 0 0);
  --popover-foreground: oklch(100% 0 0);
  --primary: oklch(100% 0 0);
  --primary-foreground: oklch(13.98% 0 0);
  --secondary: oklch(22.64% 0 0);
  --secondary-foreground: oklch(100% 0 0);
  --muted: oklch(22.64% 0 0);
  --muted-foreground: oklch(68.3% 0 0);
  --accent: oklch(19.13% 0 0);
  --accent-foreground: oklch(100% 0 0);
  --destructive: oklch(70.22% .1892 22.2279);
  --destructive-foreground: oklch(98.51% 0 0);
  --border: oklch(26.86% 0 0);
  --input: oklch(22.64% 0 0);
  --ring: oklch(66.9% .1837 248.807);
  --hover: oklch(100% 0 0 / .06);
  --active: oklch(100% 0 0 / .1);
  --focus-ring: var(--ring);
  --chart-1: oklch(87.81% .1688 91.8567);
  --chart-2: oklch(77.24% .1728 65.367);
  --chart-3: oklch(66.71% .1685 53.3814);
  --chart-4: oklch(55.7% .1583 45.3594);
  --chart-5: oklch(47.47% .1358 44.9806);
  --sidebar: oklch(19.13% 0 0);
  --sidebar-foreground: oklch(100% 0 0);
  --sidebar-primary: oklch(66.9% .1837 248.807);
  --sidebar-primary-foreground: oklch(100% 0 0);
  --sidebar-accent: oklch(22.64% 0 0);
  --sidebar-accent-foreground: oklch(100% 0 0);
  --sidebar-border: oklch(21.78% 0 0);
  --sidebar-ring: oklch(66.9% .1837 248.807);
  --radius: .625rem;
  --kortix-base: var(--color-ring);
  --kortix-blue: oklch(65.2% .177 252.624);
  --kortix-yellow: oklch(73.2% .15 90.688);
  --kortix-orange: oklch(69.1% .142 71.784);
  --kortix-green: oklch(58.1% .165 146.619);
  --kortix-purple: oklch(67.5% .131 306.212);
  --kortix-red: oklch(64.8% .202 24.745);
}

@keyframes spinner-orbit {
  to {
    transform: rotate(360deg);
  }
}

@keyframes spinner-spin {
  to {
    transform: rotate(360deg);
  }
}

@keyframes spinner-dash {
  0% {
    stroke-dashoffset: 58px;
    transform: rotate(0);
  }

  50% {
    stroke-dashoffset: 14px;
    transform: rotate(180deg);
  }

  100% {
    stroke-dashoffset: 58px;
    transform: rotate(360deg);
  }
}

.animate-spinner-orbit {
  transform-origin: center;
  animation: 1.4s linear infinite spinner-orbit;
}

.animate-spinner-spin {
  transform-origin: center;
  animation: 1s linear infinite spinner-spin;
}

.animate-spinner-dash {
  transform-origin: center;
  transform-box: fill-box;
  stroke-dasharray: 62.83;
  animation: 1.4s cubic-bezier(.77, 0, .175, 1) infinite spinner-dash;
}

@keyframes spinner-spokes {
  to {
    transform: rotate(360deg);
  }
}

.animate-spinner-spokes {
  transform-origin: center;
  animation: .8s steps(8, end) infinite spinner-spokes;
}

@media (prefers-reduced-motion: reduce) {
  .animate-spinner-orbit, .animate-spinner-spin {
    animation: 1.4s linear infinite spinner-orbit;
  }

  .animate-spinner-dash {
    stroke-dashoffset: 34px;
    animation: none;
    transform: none;
  }

  .animate-spinner-spokes {
    animation: 1.4s linear infinite spinner-spokes;
  }
}

@property --tw-space-y-reverse {
  syntax: "*";
  inherits: false;
  initial-value: 0;
}

@property --tw-border-style {
  syntax: "*";
  inherits: false;
  initial-value: solid;
}

@property --tw-font-weight {
  syntax: "*";
  inherits: false
}

@property --tw-shadow {
  syntax: "*";
  inherits: false;
  initial-value: 0 0 #0000;
}

@property --tw-shadow-color {
  syntax: "*";
  inherits: false
}

@property --tw-shadow-alpha {
  syntax: "<percentage>";
  inherits: false;
  initial-value: 100%;
}

@property --tw-inset-shadow {
  syntax: "*";
  inherits: false;
  initial-value: 0 0 #0000;
}

@property --tw-inset-shadow-color {
  syntax: "*";
  inherits: false
}

@property --tw-inset-shadow-alpha {
  syntax: "<percentage>";
  inherits: false;
  initial-value: 100%;
}

@property --tw-ring-color {
  syntax: "*";
  inherits: false
}

@property --tw-ring-shadow {
  syntax: "*";
  inherits: false;
  initial-value: 0 0 #0000;
}

@property --tw-inset-ring-color {
  syntax: "*";
  inherits: false
}

@property --tw-inset-ring-shadow {
  syntax: "*";
  inherits: false;
  initial-value: 0 0 #0000;
}

@property --tw-ring-inset {
  syntax: "*";
  inherits: false
}

@property --tw-ring-offset-width {
  syntax: "<length>";
  inherits: false;
  initial-value: 0;
}

@property --tw-ring-offset-color {
  syntax: "*";
  inherits: false;
  initial-value: #fff;
}

@property --tw-ring-offset-shadow {
  syntax: "*";
  inherits: false;
  initial-value: 0 0 #0000;
}
`;
