// @ts-check
const eslint = require('@typescript-eslint/eslint-plugin');
const tsParser = require('@typescript-eslint/parser');
const js = require('@eslint/js');
const globals = require('globals');

module.exports = [
  {
    ignores: [
      'dist/**', 'node_modules/**', '.deliveryos/**', 'build/**',
      'src-tauri/target/**', 'examples/**',
      // Generated by scripts/generate-vendored-*.mjs and shipped minified.
      // Linting someone else's bundle reports their style, not ours.
      'src-tauri/spike-ui/vendor/**',
    ],
  },
  {
    // The desktop frontend. Plain browser scripts loaded by <script> tags --
    // no bundler, no module system, so `sourceType: 'script'`.
    //
    // Until this block existed, `--print-config` reported `rules: 0` for all
    // 7,464 lines of app.js. It was never in `ignores`; it simply matched no
    // config that carried any rules, which looks identical from the outside
    // and is far easier to miss than an explicit exclusion. The first run
    // found dead code carrying a five-line comment describing behaviour that
    // had moved elsewhere.
    files: ['src-tauri/spike-ui/**/*.js'],
    languageOptions: {
      ecmaVersion: 2022,
      sourceType: 'script',
      globals: {
        ...globals.browser,
        // Vendored libraries that attach themselves to `window` via <script>
        // tags in index.html. They are real globals at run time with no import
        // to declare them, so without these three every use is `no-undef`.
        marked: 'readonly',
        Terminal: 'readonly',
        FitAddon: 'readonly',
      },
    },
    rules: js.configs.recommended.rules,
  },
  {
    files: ['**/*.ts'],
    languageOptions: {
      parser: tsParser,
      parserOptions: {
        sourceType: 'module',
      },
    },
    plugins: {
      '@typescript-eslint': eslint,
    },
    rules: {
      ...eslint.configs.recommended.rules,
      '@typescript-eslint/no-unused-vars': [
        'warn',
        { argsIgnorePattern: '^_', varsIgnorePattern: '^_' },
      ],
    },
  },
  {
    // stdout is a wire, not a log. `src/sidecar.ts` and the MCP server both
    // speak JSON-RPC over it, and the engine is called from inside both -- so
    // a stray `console.log` anywhere in this set corrupts a protocol stream
    // and surfaces to the user as an unexplained parse error, far from its
    // cause. The comment at `src/sidecar.ts:5-8` had asserted this rule since
    // the sidecar was written; nothing enforced it. This does.
    //
    // The CLI's own command files are deliberately NOT in this set: printing
    // is their entire job. `src/cli/commands/mcp.ts` is the one exception,
    // because copying a neighbouring command's opening `console.log` into it
    // is the obvious mistake.
    files: ['src/mcp/**/*.ts', 'src/engine/**/*.ts', 'src/sidecar.ts', 'src/cli/commands/mcp.ts'],
    rules: {
      'no-console': 'error',
    },
  },
];
