/* AUTO-GENERATED by scripts/gen-preview-css.mjs -- do not edit by hand.
 * Real Tailwind v4 output for ButtonGroup's own classes, compiled against
 * tokens/kortix-tokens.css. Inlined because the preview sandbox runs
 * Tailwind v3 and cannot resolve Suna's v4 @theme tokens. */
export const PREVIEW_CSS = `/*! tailwindcss v4.3.3 | MIT License | https://tailwindcss.com */

  @supports (((-webkit-hyphens: none)) and (not (margin-trim: inline))) or ((-moz-orient: inline) and (not (color: rgb(from red r g b)))) {
    *, :before, :after, ::backdrop {
      --tw-space-y-reverse: 0;
      --tw-border-style: solid;
      --tw-font-weight: initial;
      --tw-shadow: 0 0 #0000;
      --tw-shadow-color: initial;
      --tw-shadow-alpha: 100%;
      --tw-inset-shadow: 0 0 #0000;
      --tw-inset-shadow-color: initial;
      --tw-inset-shadow-alpha: 100%;
      --tw-ring-color: initial;
      --tw-ring-shadow: 0 0 #0000;
      --tw-inset-ring-color: initial;
      --tw-inset-ring-shadow: 0 0 #0000;
      --tw-ring-inset: initial;
      --tw-ring-offset-width: 0px;
      --tw-ring-offset-color: #fff;
      --tw-ring-offset-shadow: 0 0 #0000;
      --tw-outline-style: solid;
      --tw-duration: initial;
      --tw-ease: initial;
    }
  }



  :root, :host {
    --spacing: .25rem;
    --font-weight-medium: 500;
    --default-transition-duration: .15s;
    --default-transition-timing-function: cubic-bezier(.4, 0, .2, 1);
    --default-font-family: var(--font-roobert);
    --default-mono-font-family: var(--font-roobert-mono);
    --color-ring: var(--ring);
  }



  *, :after, :before, ::backdrop {
    box-sizing: border-box;
    border: 0 solid;
    margin: 0;
    padding: 0;
  }

  ::file-selector-button {
    box-sizing: border-box;
    border: 0 solid;
    margin: 0;
    padding: 0;
  }

  html, :host {
    -webkit-text-size-adjust: 100%;
    tab-size: 4;
    line-height: 1.5;
    font-family: var(--default-font-family, -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, "Helvetica Neue", "Noto Sans", Arial, sans-serif, "Apple Color Emoji", "Segoe UI Emoji", "Segoe UI Symbol", "Noto Color Emoji");
    font-feature-settings: var(--default-font-feature-settings, normal);
    font-variation-settings: var(--default-font-variation-settings, normal);
    -webkit-tap-highlight-color: transparent;
  }

  hr {
    height: 0;
    color: inherit;
    border-top-width: 1px;
  }

  abbr:where([title]) {
    -webkit-text-decoration: underline dotted;
    text-decoration: underline dotted;
  }

  h1, h2, h3, h4, h5, h6 {
    font-size: inherit;
    font-weight: inherit;
  }

  a {
    color: inherit;
    -webkit-text-decoration: inherit;
    -webkit-text-decoration: inherit;
    -webkit-text-decoration: inherit;
    text-decoration: inherit;
  }

  b, strong {
    font-weight: bolder;
  }

  code, kbd, samp, pre {
    font-family: var(--default-mono-font-family, ui-monospace, SFMono-Regular, Menlo, Monaco, Consolas, "Liberation Mono", "Courier New", monospace);
    font-feature-settings: var(--default-mono-font-feature-settings, normal);
    font-variation-settings: var(--default-mono-font-variation-settings, normal);
    font-size: 1em;
  }

  small {
    font-size: 80%;
  }

  sub, sup {
    vertical-align: baseline;
    font-size: 75%;
    line-height: 0;
    position: relative;
  }

  sub {
    bottom: -.25em;
  }

  sup {
    top: -.5em;
  }

  table {
    text-indent: 0;
    border-color: inherit;
    border-collapse: collapse;
  }

  :-moz-focusring:where(:not(iframe)) {
    outline: auto;
  }

  progress {
    vertical-align: baseline;
  }

  summary {
    display: list-item;
  }

  ol, ul, menu {
    list-style: none;
  }

  img, svg, video, canvas, audio, iframe, embed, object {
    vertical-align: middle;
    display: block;
  }

  img, video {
    max-width: 100%;
    height: auto;
  }

  button, input, select, optgroup, textarea {
    font: inherit;
    font-feature-settings: inherit;
    font-variation-settings: inherit;
    letter-spacing: inherit;
    color: inherit;
    opacity: 1;
    background-color: #0000;
    border-radius: 0;
  }

  ::file-selector-button {
    font: inherit;
    font-feature-settings: inherit;
    font-variation-settings: inherit;
    letter-spacing: inherit;
    color: inherit;
    opacity: 1;
    background-color: #0000;
    border-radius: 0;
  }

  :where(select:is([multiple], [size])) optgroup {
    font-weight: bolder;
  }

  :where(select:is([multiple], [size])) optgroup option {
    padding-inline-start: 20px;
  }

  ::file-selector-button {
    margin-inline-end: 4px;
  }

  ::placeholder {
    opacity: 1;
  }

  @supports (not ((-webkit-appearance: -apple-pay-button))) or (contain-intrinsic-size: 1px) {
    ::placeholder {
      color: currentColor;
    }

    @supports (color: color-mix(in lab, red, red)) {
      ::placeholder {
        color: color-mix(in oklab, currentcolor 50%, transparent);
      }
    }
  }

  textarea {
    resize: vertical;
  }

  ::-webkit-search-decoration {
    -webkit-appearance: none;
  }

  ::-webkit-date-and-time-value {
    min-height: 1lh;
    text-align: inherit;
  }

  ::-webkit-datetime-edit {
    display: inline-flex;
  }

  ::-webkit-datetime-edit-fields-wrapper {
    padding: 0;
  }

  ::-webkit-datetime-edit {
    padding-block: 0;
  }

  ::-webkit-datetime-edit-year-field {
    padding-block: 0;
  }

  ::-webkit-datetime-edit-month-field {
    padding-block: 0;
  }

  ::-webkit-datetime-edit-day-field {
    padding-block: 0;
  }

  ::-webkit-datetime-edit-hour-field {
    padding-block: 0;
  }

  ::-webkit-datetime-edit-minute-field {
    padding-block: 0;
  }

  ::-webkit-datetime-edit-second-field {
    padding-block: 0;
  }

  ::-webkit-datetime-edit-millisecond-field {
    padding-block: 0;
  }

  ::-webkit-datetime-edit-meridiem-field {
    padding-block: 0;
  }

  ::-webkit-calendar-picker-indicator {
    line-height: 1;
  }

  :-moz-ui-invalid {
    box-shadow: none;
  }

  button, input:where([type="button"], [type="reset"], [type="submit"]) {
    appearance: button;
  }

  ::file-selector-button {
    appearance: button;
  }

  ::-webkit-inner-spin-button {
    height: auto;
  }

  ::-webkit-outer-spin-button {
    height: auto;
  }

  [hidden]:where(:not([hidden="until-found"])) {
    display: none !important;
  }

  :root {
    color-scheme: light;
  }

  .dark {
    color-scheme: dark;
  }





  .relative {
    position: relative;
  }

  .m-0\\! {
    margin: 0 !important;
  }

  .flex {
    display: flex;
  }

  .size-6 {
    width: calc(var(--spacing) * 6);
    height: calc(var(--spacing) * 6);
  }

  .size-7 {
    width: calc(var(--spacing) * 7);
    height: calc(var(--spacing) * 7);
  }

  .size-8 {
    width: calc(var(--spacing) * 8);
    height: calc(var(--spacing) * 8);
  }

  .size-9 {
    width: calc(var(--spacing) * 9);
    height: calc(var(--spacing) * 9);
  }

  .size-10 {
    width: calc(var(--spacing) * 10);
    height: calc(var(--spacing) * 10);
  }

  .h-7 {
    height: calc(var(--spacing) * 7);
  }

  .h-8 {
    height: calc(var(--spacing) * 8);
  }

  .h-9 {
    height: calc(var(--spacing) * 9);
  }

  .h-10 {
    height: calc(var(--spacing) * 10);
  }

  .h-12 {
    height: calc(var(--spacing) * 12);
  }

  .w-fit {
    width: fit-content;
  }

  .w-full {
    width: 100%;
  }

  .shrink-0 {
    flex-shrink: 0;
  }

  .cursor-pointer {
    cursor: pointer;
  }

  .flex-col {
    flex-direction: column;
  }

  .flex-wrap {
    flex-wrap: wrap;
  }

  .items-center {
    align-items: center;
  }

  .items-start {
    align-items: flex-start;
  }

  .items-stretch {
    align-items: stretch;
  }

  .justify-center {
    justify-content: center;
  }

  .gap-1 {
    gap: var(--spacing);
  }

  .gap-1\\.5 {
    gap: calc(var(--spacing) * 1.5);
  }

  .gap-2 {
    gap: calc(var(--spacing) * 2);
  }

  .gap-3 {
    gap: calc(var(--spacing) * 3);
  }

  .gap-10 {
    gap: calc(var(--spacing) * 10);
  }

  :where(.space-y-2 > :not(:last-child)) {
    --tw-space-y-reverse: 0;
    margin-block-start: calc(calc(var(--spacing) * 2) * var(--tw-space-y-reverse));
    margin-block-end: calc(calc(var(--spacing) * 2) * calc(1 - var(--tw-space-y-reverse)));
  }

  :where(.space-y-6 > :not(:last-child)) {
    --tw-space-y-reverse: 0;
    margin-block-start: calc(calc(var(--spacing) * 6) * var(--tw-space-y-reverse));
    margin-block-end: calc(calc(var(--spacing) * 6) * calc(1 - var(--tw-space-y-reverse)));
  }

  .self-stretch {
    align-self: stretch;
  }

  .rounded-md {
    border-radius: calc(var(--radius) - 2px);
  }

  .rounded-sm {
    border-radius: calc(var(--radius) - 4px);
  }

  .border {
    border-style: var(--tw-border-style);
    border-width: 1px;
  }

  .border-background\\/10 {
    border-color: var(--background);
  }

  @supports (color: color-mix(in lab, red, red)) {
    .border-background\\/10 {
      border-color: color-mix(in oklab, var(--background) 10%, transparent);
    }
  }

  .border-border {
    border-color: var(--border);
  }

  .border-foreground\\/10 {
    border-color: var(--foreground);
  }

  @supports (color: color-mix(in lab, red, red)) {
    .border-foreground\\/10 {
      border-color: color-mix(in oklab, var(--foreground) 10%, transparent);
    }
  }

  .border-primary\\/10 {
    border-color: var(--primary);
  }

  @supports (color: color-mix(in lab, red, red)) {
    .border-primary\\/10 {
      border-color: color-mix(in oklab, var(--primary) 10%, transparent);
    }
  }

  .bg-\\[\\#fafafa\\] {
    background-color: #fafafa;
  }

  .bg-background {
    background-color: var(--background);
  }

  .bg-border {
    background-color: var(--border);
  }

  .bg-destructive, .bg-destructive\\/80 {
    background-color: var(--destructive);
  }

  @supports (color: color-mix(in lab, red, red)) {
    .bg-destructive\\/80 {
      background-color: color-mix(in oklab, var(--destructive) 80%, transparent);
    }
  }

  .bg-foreground, .bg-foreground\\/5 {
    background-color: var(--foreground);
  }

  @supports (color: color-mix(in lab, red, red)) {
    .bg-foreground\\/5 {
      background-color: color-mix(in oklab, var(--foreground) 5%, transparent);
    }
  }

  .bg-foreground\\/80 {
    background-color: var(--foreground);
  }

  @supports (color: color-mix(in lab, red, red)) {
    .bg-foreground\\/80 {
      background-color: color-mix(in oklab, var(--foreground) 80%, transparent);
    }
  }

  .bg-foreground\\/90 {
    background-color: var(--foreground);
  }

  @supports (color: color-mix(in lab, red, red)) {
    .bg-foreground\\/90 {
      background-color: color-mix(in oklab, var(--foreground) 90%, transparent);
    }
  }

  .bg-input {
    background-color: var(--input);
  }

  .bg-kortix-blue, .bg-kortix-blue\\/10 {
    background-color: var(--kortix-blue);
  }

  @supports (color: color-mix(in lab, red, red)) {
    .bg-kortix-blue\\/10 {
      background-color: color-mix(in oklab, var(--kortix-blue) 10%, transparent);
    }
  }

  .bg-kortix-blue\\/80 {
    background-color: var(--kortix-blue);
  }

  @supports (color: color-mix(in lab, red, red)) {
    .bg-kortix-blue\\/80 {
      background-color: color-mix(in oklab, var(--kortix-blue) 80%, transparent);
    }
  }

  .bg-kortix-blue\\/90 {
    background-color: var(--kortix-blue);
  }

  @supports (color: color-mix(in lab, red, red)) {
    .bg-kortix-blue\\/90 {
      background-color: color-mix(in oklab, var(--kortix-blue) 90%, transparent);
    }
  }

  .bg-kortix-green\\/80 {
    background-color: var(--kortix-green);
  }

  @supports (color: color-mix(in lab, red, red)) {
    .bg-kortix-green\\/80 {
      background-color: color-mix(in oklab, var(--kortix-green) 80%, transparent);
    }
  }

  .bg-kortix-red\\/80 {
    background-color: var(--kortix-red);
  }

  @supports (color: color-mix(in lab, red, red)) {
    .bg-kortix-red\\/80 {
      background-color: color-mix(in oklab, var(--kortix-red) 80%, transparent);
    }
  }

  .bg-kortix-yellow\\/80 {
    background-color: var(--kortix-yellow);
  }

  @supports (color: color-mix(in lab, red, red)) {
    .bg-kortix-yellow\\/80 {
      background-color: color-mix(in oklab, var(--kortix-yellow) 80%, transparent);
    }
  }

  .bg-muted {
    background-color: var(--muted);
  }

  .bg-popover {
    background-color: var(--popover);
  }

  .bg-secondary {
    background-color: var(--secondary);
  }

  .bg-transparent {
    background-color: #0000;
  }

  .p-6 {
    padding: calc(var(--spacing) * 6);
  }

  .px-2\\.5 {
    padding-inline: calc(var(--spacing) * 2.5);
  }

  .px-3 {
    padding-inline: calc(var(--spacing) * 3);
  }

  .px-4 {
    padding-inline: calc(var(--spacing) * 4);
  }

  .px-6 {
    padding-inline: calc(var(--spacing) * 6);
  }

  .px-8 {
    padding-inline: calc(var(--spacing) * 8);
  }

  .py-2 {
    padding-block: calc(var(--spacing) * 2);
  }

  .pt-4 {
    padding-top: calc(var(--spacing) * 4);
  }

  .text-center {
    text-align: center;
  }

  .font-sans {
    font-family: var(--font-roobert);
  }

  .text-sm {
    font-size: .875rem;
    line-height: var(--tw-leading, calc(1.25 / .875));
  }

  .text-xs {
    font-size: .8125rem;
    line-height: var(--tw-leading, calc(1 / .8125));
  }

  .font-medium {
    --tw-font-weight: var(--font-weight-medium);
    font-weight: var(--font-weight-medium);
  }

  .whitespace-nowrap {
    white-space: nowrap;
  }

  .text-\\[\\#0a0a0a\\] {
    color: #0a0a0a;
  }

  .text-accent-foreground {
    color: var(--accent-foreground);
  }

  .text-background {
    color: var(--background);
  }

  .text-foreground, .text-foreground\\/80 {
    color: var(--foreground);
  }

  @supports (color: color-mix(in lab, red, red)) {
    .text-foreground\\/80 {
      color: color-mix(in oklab, var(--foreground) 80%, transparent);
    }
  }

  .text-kortix-blue {
    color: var(--kortix-blue);
  }

  .text-muted-foreground {
    color: var(--muted-foreground);
  }

  .text-sidebar-foreground {
    color: var(--sidebar-foreground);
  }

  .underline-offset-4 {
    text-underline-offset: 4px;
  }

  .shadow-none {
    --tw-shadow: 0 0 #0000;
    box-shadow: var(--tw-inset-shadow), var(--tw-inset-ring-shadow), var(--tw-ring-offset-shadow), var(--tw-ring-shadow), var(--tw-shadow);
  }

  .shadow-xs {
    --tw-shadow: 0 1px 2px 0 var(--tw-shadow-color, light-dark(oklch(0% 0 0 / .04), oklch(0% 0 0 / .18))), 0 0 4px 0 var(--tw-shadow-color, light-dark(oklch(0% 0 0 / .03), oklch(0% 0 0 / .12)));
    box-shadow: var(--tw-inset-shadow), var(--tw-inset-ring-shadow), var(--tw-ring-offset-shadow), var(--tw-ring-shadow), var(--tw-shadow);
  }

  .outline {
    outline-style: var(--tw-outline-style);
    outline-width: 1px;
  }

  .outline-foreground {
    outline-color: var(--foreground);
  }

  .outline-sidebar {
    outline-color: var(--sidebar);
  }

  .transition-all {
    transition-property: all;
    transition-timing-function: var(--tw-ease, var(--default-transition-timing-function));
    transition-duration: var(--tw-duration, var(--default-transition-duration));
  }

  .transition-colors {
    transition-property: color, background-color, border-color, outline-color, text-decoration-color, fill, stroke, --tw-gradient-from, --tw-gradient-via, --tw-gradient-to;
    transition-timing-function: var(--tw-ease, var(--default-transition-timing-function));
    transition-duration: var(--tw-duration, var(--default-transition-duration));
  }

  .duration-200 {
    --tw-duration: .2s;
    transition-duration: .2s;
  }

  .ease-in {
    --tw-ease: cubic-bezier(.4, 0, 1, 1);
    transition-timing-function: cubic-bezier(.4, 0, 1, 1);
  }

  .outline-none {
    --tw-outline-style: none;
    outline-style: none;
  }

  @media (hover: hover) {
    .hover\\:bg-\\[\\#fafafa\\]\\/95:hover {
      background-color: oklab(98.5104% -1.19209e-7 5.96046e-8 / .95);
    }

    .hover\\:bg-background\\/50:hover {
      background-color: var(--background);
    }

    @supports (color: color-mix(in lab, red, red)) {
      .hover\\:bg-background\\/50:hover {
        background-color: color-mix(in oklab, var(--background) 50%, transparent);
      }
    }

    .hover\\:bg-background\\/90:hover {
      background-color: var(--background);
    }

    @supports (color: color-mix(in lab, red, red)) {
      .hover\\:bg-background\\/90:hover {
        background-color: color-mix(in oklab, var(--background) 90%, transparent);
      }
    }

    .hover\\:bg-destructive\\/85:hover {
      background-color: var(--destructive);
    }

    @supports (color: color-mix(in lab, red, red)) {
      .hover\\:bg-destructive\\/85:hover {
        background-color: color-mix(in oklab, var(--destructive) 85%, transparent);
      }
    }

    .hover\\:bg-destructive\\/90:hover {
      background-color: var(--destructive);
    }

    @supports (color: color-mix(in lab, red, red)) {
      .hover\\:bg-destructive\\/90:hover {
        background-color: color-mix(in oklab, var(--destructive) 90%, transparent);
      }
    }

    .hover\\:bg-foreground:hover, .hover\\:bg-foreground\\/5:hover {
      background-color: var(--foreground);
    }

    @supports (color: color-mix(in lab, red, red)) {
      .hover\\:bg-foreground\\/5:hover {
        background-color: color-mix(in oklab, var(--foreground) 5%, transparent);
      }
    }

    .hover\\:bg-foreground\\/8:hover {
      background-color: var(--foreground);
    }

    @supports (color: color-mix(in lab, red, red)) {
      .hover\\:bg-foreground\\/8:hover {
        background-color: color-mix(in oklab, var(--foreground) 8%, transparent);
      }
    }

    .hover\\:bg-foreground\\/10:hover {
      background-color: var(--foreground);
    }

    @supports (color: color-mix(in lab, red, red)) {
      .hover\\:bg-foreground\\/10:hover {
        background-color: color-mix(in oklab, var(--foreground) 10%, transparent);
      }
    }

    .hover\\:bg-foreground\\/90:hover {
      background-color: var(--foreground);
    }

    @supports (color: color-mix(in lab, red, red)) {
      .hover\\:bg-foreground\\/90:hover {
        background-color: color-mix(in oklab, var(--foreground) 90%, transparent);
      }
    }

    .hover\\:bg-input:hover, .hover\\:bg-input\\/95:hover {
      background-color: var(--input);
    }

    @supports (color: color-mix(in lab, red, red)) {
      .hover\\:bg-input\\/95:hover {
        background-color: color-mix(in oklab, var(--input) 95%, transparent);
      }
    }

    .hover\\:bg-kortix-blue\\/20:hover {
      background-color: var(--kortix-blue);
    }

    @supports (color: color-mix(in lab, red, red)) {
      .hover\\:bg-kortix-blue\\/20:hover {
        background-color: color-mix(in oklab, var(--kortix-blue) 20%, transparent);
      }
    }

    .hover\\:bg-kortix-blue\\/85:hover {
      background-color: var(--kortix-blue);
    }

    @supports (color: color-mix(in lab, red, red)) {
      .hover\\:bg-kortix-blue\\/85:hover {
        background-color: color-mix(in oklab, var(--kortix-blue) 85%, transparent);
      }
    }

    .hover\\:bg-kortix-blue\\/90:hover {
      background-color: var(--kortix-blue);
    }

    @supports (color: color-mix(in lab, red, red)) {
      .hover\\:bg-kortix-blue\\/90:hover {
        background-color: color-mix(in oklab, var(--kortix-blue) 90%, transparent);
      }
    }

    .hover\\:bg-kortix-green\\/85:hover {
      background-color: var(--kortix-green);
    }

    @supports (color: color-mix(in lab, red, red)) {
      .hover\\:bg-kortix-green\\/85:hover {
        background-color: color-mix(in oklab, var(--kortix-green) 85%, transparent);
      }
    }

    .hover\\:bg-kortix-red\\/85:hover {
      background-color: var(--kortix-red);
    }

    @supports (color: color-mix(in lab, red, red)) {
      .hover\\:bg-kortix-red\\/85:hover {
        background-color: color-mix(in oklab, var(--kortix-red) 85%, transparent);
      }
    }

    .hover\\:bg-kortix-yellow\\/85:hover {
      background-color: var(--kortix-yellow);
    }

    @supports (color: color-mix(in lab, red, red)) {
      .hover\\:bg-kortix-yellow\\/85:hover {
        background-color: color-mix(in oklab, var(--kortix-yellow) 85%, transparent);
      }
    }

    .hover\\:bg-muted\\/90:hover {
      background-color: var(--muted);
    }

    @supports (color: color-mix(in lab, red, red)) {
      .hover\\:bg-muted\\/90:hover {
        background-color: color-mix(in oklab, var(--muted) 90%, transparent);
      }
    }

    .hover\\:bg-secondary:hover, .hover\\:bg-secondary\\/90:hover {
      background-color: var(--secondary);
    }

    @supports (color: color-mix(in lab, red, red)) {
      .hover\\:bg-secondary\\/90:hover {
        background-color: color-mix(in oklab, var(--secondary) 90%, transparent);
      }
    }

    .hover\\:bg-sidebar:hover {
      background-color: var(--sidebar);
    }

    .hover\\:bg-sidebar-accent\\/40:hover {
      background-color: var(--sidebar-accent);
    }

    @supports (color: color-mix(in lab, red, red)) {
      .hover\\:bg-sidebar-accent\\/40:hover {
        background-color: color-mix(in oklab, var(--sidebar-accent) 40%, transparent);
      }
    }

    .hover\\:bg-sidebar-accent\\/80:hover {
      background-color: var(--sidebar-accent);
    }

    @supports (color: color-mix(in lab, red, red)) {
      .hover\\:bg-sidebar-accent\\/80:hover {
        background-color: color-mix(in oklab, var(--sidebar-accent) 80%, transparent);
      }
    }

    .hover\\:bg-transparent:hover {
      background-color: #0000;
    }

    .hover\\:text-background:hover {
      color: var(--background);
    }

    .hover\\:text-foreground:hover {
      color: var(--foreground);
    }

    .hover\\:text-primary:hover {
      color: var(--primary);
    }

    .hover\\:text-sidebar-accent-foreground:hover {
      color: var(--sidebar-accent-foreground);
    }

    .hover\\:underline:hover {
      text-decoration-line: underline;
    }
  }

  .focus-visible\\:ring-2:focus-visible {
    --tw-ring-shadow: var(--tw-ring-inset, ) 0 0 0 calc(2px + var(--tw-ring-offset-width)) var(--tw-ring-color, currentcolor);
    box-shadow: var(--tw-inset-shadow), var(--tw-inset-ring-shadow), var(--tw-ring-offset-shadow), var(--tw-ring-shadow), var(--tw-shadow);
  }

  .focus-visible\\:ring-\\[0\\.6px\\]:focus-visible {
    --tw-ring-shadow: var(--tw-ring-inset, ) 0 0 0 calc(.6px + var(--tw-ring-offset-width)) var(--tw-ring-color, currentcolor);
    box-shadow: var(--tw-inset-shadow), var(--tw-inset-ring-shadow), var(--tw-ring-offset-shadow), var(--tw-ring-shadow), var(--tw-shadow);
  }

  .focus-visible\\:ring-destructive\\/35:focus-visible {
    --tw-ring-color: var(--destructive);
  }

  @supports (color: color-mix(in lab, red, red)) {
    .focus-visible\\:ring-destructive\\/35:focus-visible {
      --tw-ring-color: color-mix(in oklab, var(--destructive) 35%, transparent);
    }
  }

  .focus-visible\\:ring-kortix-base:focus-visible {
    --tw-ring-color: var(--kortix-base);
  }

  .focus-visible\\:ring-offset-1:focus-visible {
    --tw-ring-offset-width: 1px;
    --tw-ring-offset-shadow: var(--tw-ring-inset, ) 0 0 0 var(--tw-ring-offset-width) var(--tw-ring-offset-color);
  }

  .focus-visible\\:ring-offset-4:focus-visible {
    --tw-ring-offset-width: 4px;
    --tw-ring-offset-shadow: var(--tw-ring-inset, ) 0 0 0 var(--tw-ring-offset-width) var(--tw-ring-offset-color);
  }

  .focus-visible\\:outline-none:focus-visible {
    --tw-outline-style: none;
    outline-style: none;
  }

  .disabled\\:pointer-events-none:disabled {
    pointer-events: none;
  }

  .disabled\\:opacity-50:disabled {
    opacity: .5;
  }

  :where([data-slot="button-group"]) .in-data-\\[slot\\=button-group\\]\\:rounded-2xl {
    border-radius: 1rem;
  }

  .has-data-\\[icon\\=inline-end\\]\\:pr-1\\.5:has([data-icon="inline-end"]) {
    padding-right: calc(var(--spacing) * 1.5);
  }

  .has-data-\\[icon\\=inline-start\\]\\:pl-1\\.5:has([data-icon="inline-start"]) {
    padding-left: calc(var(--spacing) * 1.5);
  }

  .has-\\[\\>\\[data-slot\\=button-group\\]\\]\\:gap-2:has( > [data-slot="button-group"]) {
    gap: calc(var(--spacing) * 2);
  }

  .has-\\[\\>svg\\]\\:px-2:has( > svg) {
    padding-inline: calc(var(--spacing) * 2);
  }

  .has-\\[\\>svg\\]\\:px-2\\.5:has( > svg) {
    padding-inline: calc(var(--spacing) * 2.5);
  }

  .has-\\[\\>svg\\]\\:px-3:has( > svg) {
    padding-inline: calc(var(--spacing) * 3);
  }

  .has-\\[\\>svg\\]\\:px-4:has( > svg) {
    padding-inline: calc(var(--spacing) * 4);
  }

  .has-\\[\\>svg\\]\\:px-6:has( > svg) {
    padding-inline: calc(var(--spacing) * 6);
  }

  .aria-invalid\\:border-destructive[aria-invalid="true"] {
    border-color: var(--destructive);
  }

  .aria-invalid\\:ring-destructive\\/20[aria-invalid="true"] {
    --tw-ring-color: var(--destructive);
  }

  @supports (color: color-mix(in lab, red, red)) {
    .aria-invalid\\:ring-destructive\\/20[aria-invalid="true"] {
      --tw-ring-color: color-mix(in oklab, var(--destructive) 20%, transparent);
    }
  }

  .data-\\[orientation\\=horizontal\\]\\:h-px[data-orientation="horizontal"] {
    height: 1px;
  }

  .data-\\[orientation\\=horizontal\\]\\:w-full[data-orientation="horizontal"] {
    width: 100%;
  }

  .data-\\[orientation\\=vertical\\]\\:h-auto[data-orientation="vertical"] {
    height: auto;
  }

  .data-\\[orientation\\=vertical\\]\\:h-full[data-orientation="vertical"] {
    height: 100%;
  }

  .data-\\[orientation\\=vertical\\]\\:w-px[data-orientation="vertical"] {
    width: 1px;
  }

  .data-\\[state\\=open\\]\\:ring-0[data-state="open"] {
    --tw-ring-shadow: var(--tw-ring-inset, ) 0 0 0 calc(0px + var(--tw-ring-offset-width)) var(--tw-ring-color, currentcolor);
    box-shadow: var(--tw-inset-shadow), var(--tw-inset-ring-shadow), var(--tw-ring-offset-shadow), var(--tw-ring-shadow), var(--tw-shadow);
  }

  @media (min-width: 40rem) {
    .sm\\:h-8 {
      height: calc(var(--spacing) * 8);
    }

    .sm\\:gap-1\\.5 {
      gap: calc(var(--spacing) * 1.5);
    }

    .sm\\:px-3 {
      padding-inline: calc(var(--spacing) * 3);
    }

    .sm\\:has-\\[\\>svg\\]\\:px-2\\.5:has( > svg) {
      padding-inline: calc(var(--spacing) * 2.5);
    }
  }

  .dark\\:bg-\\[\\#0a0a0a\\]:where(.dark, .dark *) {
    background-color: #0a0a0a;
  }

  .dark\\:bg-input\\/30:where(.dark, .dark *) {
    background-color: var(--input);
  }

  @supports (color: color-mix(in lab, red, red)) {
    .dark\\:bg-input\\/30:where(.dark, .dark *) {
      background-color: color-mix(in oklab, var(--input) 30%, transparent);
    }
  }

  .dark\\:bg-kortix-blue\\/60:where(.dark, .dark *) {
    background-color: var(--kortix-blue);
  }

  @supports (color: color-mix(in lab, red, red)) {
    .dark\\:bg-kortix-blue\\/60:where(.dark, .dark *) {
      background-color: color-mix(in oklab, var(--kortix-blue) 60%, transparent);
    }
  }

  .dark\\:text-\\[\\#fafafa\\]:where(.dark, .dark *) {
    color: #fafafa;
  }

  .dark\\:text-foreground:where(.dark, .dark *) {
    color: var(--foreground);
  }

  @media (hover: hover) {
    .dark\\:hover\\:bg-\\[\\#0a0a0a\\]\\/95:where(.dark, .dark *):hover {
      background-color: oklab(14.4788% 1.49012e-8 -7.45058e-9 / .95);
    }

    .dark\\:hover\\:bg-input\\/235:where(.dark, .dark *):hover {
      background-color: var(--input);
    }

    @supports (color: color-mix(in lab, red, red)) {
      .dark\\:hover\\:bg-input\\/235:where(.dark, .dark *):hover {
        background-color: color-mix(in oklab, var(--input) 235%, transparent);
      }
    }

    .dark\\:hover\\:bg-kortix-blue\\/50:where(.dark, .dark *):hover {
      background-color: var(--kortix-blue);
    }

    @supports (color: color-mix(in lab, red, red)) {
      .dark\\:hover\\:bg-kortix-blue\\/50:where(.dark, .dark *):hover {
        background-color: color-mix(in oklab, var(--kortix-blue) 50%, transparent);
      }
    }
  }

  .dark\\:aria-invalid\\:ring-destructive\\/40:where(.dark, .dark *)[aria-invalid="true"] {
    --tw-ring-color: var(--destructive);
  }

  @supports (color: color-mix(in lab, red, red)) {
    .dark\\:aria-invalid\\:ring-destructive\\/40:where(.dark, .dark *)[aria-invalid="true"] {
      --tw-ring-color: color-mix(in oklab, var(--destructive) 40%, transparent);
    }
  }

  .\\[\\&_svg\\]\\:pointer-events-none svg {
    pointer-events: none;
  }

  .\\[\\&_svg\\]\\:shrink-0 svg {
    flex-shrink: 0;
  }

  .\\[\\&_svg\\:not\\(\\[class\\*\\=\\'size-\\'\\]\\)\\]\\:size-3\\.5 svg:not([class*="size-"]) {
    width: calc(var(--spacing) * 3.5);
    height: calc(var(--spacing) * 3.5);
  }

  .\\[\\&_svg\\:not\\(\\[class\\*\\=\\'size-\\'\\]\\)\\]\\:size-4 svg:not([class*="size-"]) {
    width: calc(var(--spacing) * 4);
    height: calc(var(--spacing) * 4);
  }

  .\\[\\&\\>\\*\\]\\:focus-visible\\:relative > :focus-visible {
    position: relative;
  }

  .\\[\\&\\>\\*\\]\\:focus-visible\\:z-10 > :focus-visible {
    z-index: 10;
  }

  .\\[\\&\\>\\*\\:not\\(\\:first-child\\)\\]\\:rounded-t-none > :not(:first-child) {
    border-top-left-radius: 0;
    border-top-right-radius: 0;
  }

  .\\[\\&\\>\\*\\:not\\(\\:first-child\\)\\]\\:rounded-l-none > :not(:first-child) {
    border-top-left-radius: 0;
    border-bottom-left-radius: 0;
  }

  .\\[\\&\\>\\*\\:not\\(\\:first-child\\)\\]\\:border-t-0 > :not(:first-child) {
    border-top-style: var(--tw-border-style);
    border-top-width: 0;
  }

  .\\[\\&\\>\\*\\:not\\(\\:first-child\\)\\]\\:border-l-0 > :not(:first-child) {
    border-left-style: var(--tw-border-style);
    border-left-width: 0;
  }

  .\\[\\&\\>\\*\\:not\\(\\:last-child\\)\\]\\:rounded-r-none > :not(:last-child) {
    border-top-right-radius: 0;
    border-bottom-right-radius: 0;
  }

  .\\[\\&\\>\\*\\:not\\(\\:last-child\\)\\]\\:rounded-b-none > :not(:last-child) {
    border-bottom-right-radius: 0;
    border-bottom-left-radius: 0;
  }

  .has-\\[select\\[aria-hidden\\=true\\]\\:last-child\\]\\:\\[\\&\\>\\[data-slot\\=select-trigger\\]\\:last-of-type\\]\\:rounded-r-md:has(:is(select[aria-hidden="true"]:last-child)) > [data-slot="select-trigger"]:last-of-type {
    border-top-right-radius: calc(var(--radius) - 2px);
    border-bottom-right-radius: calc(var(--radius) - 2px);
  }

  .\\[\\&\\>\\[data-slot\\=select-trigger\\]\\:not\\(\\[class\\*\\=\\'w-\\'\\]\\)\\]\\:w-fit > [data-slot="select-trigger"]:not([class*="w-"]) {
    width: fit-content;
  }

  .\\[\\&\\>input\\]\\:flex-1 > input {
    flex: 1;
  }


:root {
  --background: oklch(100% 0 0);
  --pane: oklch(100% 0 0);
  --foreground: oklch(0% 0 0);
  --foreground-strong: var(--foreground);
  --foreground-weak: var(--muted-foreground);
  --card: oklch(96.72% 0 0);
  --card-foreground: oklch(0% 0 0);
  --popover: oklch(100% 0 0);
  --popover-foreground: oklch(0% 0 0);
  --primary: oklch(0% 0 0);
  --primary-foreground: oklch(100% 0 0);
  --secondary: oklch(94.31% 0 0);
  --secondary-foreground: oklch(0% 0 0);
  --muted: oklch(94.31% 0 0);
  --muted-foreground: oklch(51.03% 0 0);
  --accent: oklch(96.72% 0 0);
  --accent-foreground: oklch(0% 0 0);
  --destructive: oklch(58.3% .2387 28.4765);
  --destructive-foreground: oklch(98.51% 0 0);
  --border: oklch(91.28% 0 0);
  --input: oklch(94.31% 0 0);
  --ring: oklch(66.9% .1837 248.807);
  --hover: oklch(0% 0 0 / .045);
  --active: oklch(0% 0 0 / .075);
  --focus-ring: var(--ring);
  --chart-1: oklch(87.81% .1688 91.8567);
  --chart-2: oklch(77.24% .1728 65.367);
  --chart-3: oklch(66.71% .1685 53.3814);
  --chart-4: oklch(55.7% .1583 45.3594);
  --chart-5: oklch(47.47% .1358 44.9806);
  --sidebar: oklch(96.72% 0 0);
  --sidebar-foreground: oklch(0% 0 0);
  --sidebar-primary: oklch(66.9% .1837 248.807);
  --sidebar-primary-foreground: oklch(100% 0 0);
  --sidebar-accent: oklch(94.31% 0 0);
  --sidebar-accent-foreground: oklch(0% 0 0);
  --sidebar-border: oklch(91.28% 0 0);
  --sidebar-ring: oklch(66.9% .1837 248.807);
  --radius: .625rem;
  --tracking-normal: 0em;
  --spacing: .23rem;
  --kortix-base: var(--color-ring);
  --kortix-blue: oklch(65.2% .177 252.624);
  --kortix-yellow: oklch(73.2% .15 90.688);
  --kortix-orange: oklch(69.1% .142 71.784);
  --kortix-green: oklch(58.1% .165 146.619);
  --kortix-purple: oklch(67.5% .131 306.212);
  --kortix-red: oklch(64.8% .202 24.745);
  --duration-fast: .1s;
  --duration-normal: .15s;
  --duration-moderate: .2s;
  --duration-slow: .3s;
  --duration-slower: .5s;
  --ease-default: cubic-bezier(.2, 0, 0, 1);
  --ease-in: cubic-bezier(.4, 0, 1, 1);
  --ease-out: cubic-bezier(0, 0, .2, 1);
  --ease-in-out: cubic-bezier(.4, 0, .2, 1);
}

.dark {
  --background: oklch(17% 0 0);
  --pane: oklch(15.43% 0 0);
  --foreground: oklch(100% 0 0);
  --foreground-strong: var(--foreground);
  --foreground-weak: var(--muted-foreground);
  --card: oklch(19.13% 0 0);
  --card-foreground: oklch(100% 0 0);
  --popover: oklch(19.13% 0 0);
  --popover-foreground: oklch(100% 0 0);
  --primary: oklch(100% 0 0);
  --primary-foreground: oklch(13.98% 0 0);
  --secondary: oklch(22.64% 0 0);
  --secondary-foreground: oklch(100% 0 0);
  --muted: oklch(22.64% 0 0);
  --muted-foreground: oklch(68.3% 0 0);
  --accent: oklch(19.13% 0 0);
  --accent-foreground: oklch(100% 0 0);
  --destructive: oklch(70.22% .1892 22.2279);
  --destructive-foreground: oklch(98.51% 0 0);
  --border: oklch(26.86% 0 0);
  --input: oklch(22.64% 0 0);
  --ring: oklch(66.9% .1837 248.807);
  --hover: oklch(100% 0 0 / .06);
  --active: oklch(100% 0 0 / .1);
  --focus-ring: var(--ring);
  --chart-1: oklch(87.81% .1688 91.8567);
  --chart-2: oklch(77.24% .1728 65.367);
  --chart-3: oklch(66.71% .1685 53.3814);
  --chart-4: oklch(55.7% .1583 45.3594);
  --chart-5: oklch(47.47% .1358 44.9806);
  --sidebar: oklch(19.13% 0 0);
  --sidebar-foreground: oklch(100% 0 0);
  --sidebar-primary: oklch(66.9% .1837 248.807);
  --sidebar-primary-foreground: oklch(100% 0 0);
  --sidebar-accent: oklch(22.64% 0 0);
  --sidebar-accent-foreground: oklch(100% 0 0);
  --sidebar-border: oklch(21.78% 0 0);
  --sidebar-ring: oklch(66.9% .1837 248.807);
  --radius: .625rem;
  --kortix-base: var(--color-ring);
  --kortix-blue: oklch(65.2% .177 252.624);
  --kortix-yellow: oklch(73.2% .15 90.688);
  --kortix-orange: oklch(69.1% .142 71.784);
  --kortix-green: oklch(58.1% .165 146.619);
  --kortix-purple: oklch(67.5% .131 306.212);
  --kortix-red: oklch(64.8% .202 24.745);
}

@keyframes spinner-orbit {
  to {
    transform: rotate(360deg);
  }
}

@keyframes spinner-spin {
  to {
    transform: rotate(360deg);
  }
}

@keyframes spinner-dash {
  0% {
    stroke-dashoffset: 58px;
    transform: rotate(0);
  }

  50% {
    stroke-dashoffset: 14px;
    transform: rotate(180deg);
  }

  100% {
    stroke-dashoffset: 58px;
    transform: rotate(360deg);
  }
}

.animate-spinner-orbit {
  transform-origin: center;
  animation: 1.4s linear infinite spinner-orbit;
}

.animate-spinner-spin {
  transform-origin: center;
  animation: 1s linear infinite spinner-spin;
}

.animate-spinner-dash {
  transform-origin: center;
  transform-box: fill-box;
  stroke-dasharray: 62.83;
  animation: 1.4s cubic-bezier(.77, 0, .175, 1) infinite spinner-dash;
}

@keyframes spinner-spokes {
  to {
    transform: rotate(360deg);
  }
}

.animate-spinner-spokes {
  transform-origin: center;
  animation: .8s steps(8, end) infinite spinner-spokes;
}

@media (prefers-reduced-motion: reduce) {
  .animate-spinner-orbit, .animate-spinner-spin {
    animation: 1.4s linear infinite spinner-orbit;
  }

  .animate-spinner-dash {
    stroke-dashoffset: 34px;
    animation: none;
    transform: none;
  }

  .animate-spinner-spokes {
    animation: 1.4s linear infinite spinner-spokes;
  }
}

@property --tw-space-y-reverse {
  syntax: "*";
  inherits: false;
  initial-value: 0;
}

@property --tw-border-style {
  syntax: "*";
  inherits: false;
  initial-value: solid;
}

@property --tw-font-weight {
  syntax: "*";
  inherits: false
}

@property --tw-shadow {
  syntax: "*";
  inherits: false;
  initial-value: 0 0 #0000;
}

@property --tw-shadow-color {
  syntax: "*";
  inherits: false
}

@property --tw-shadow-alpha {
  syntax: "<percentage>";
  inherits: false;
  initial-value: 100%;
}

@property --tw-inset-shadow {
  syntax: "*";
  inherits: false;
  initial-value: 0 0 #0000;
}

@property --tw-inset-shadow-color {
  syntax: "*";
  inherits: false
}

@property --tw-inset-shadow-alpha {
  syntax: "<percentage>";
  inherits: false;
  initial-value: 100%;
}

@property --tw-ring-color {
  syntax: "*";
  inherits: false
}

@property --tw-ring-shadow {
  syntax: "*";
  inherits: false;
  initial-value: 0 0 #0000;
}

@property --tw-inset-ring-color {
  syntax: "*";
  inherits: false
}

@property --tw-inset-ring-shadow {
  syntax: "*";
  inherits: false;
  initial-value: 0 0 #0000;
}

@property --tw-ring-inset {
  syntax: "*";
  inherits: false
}

@property --tw-ring-offset-width {
  syntax: "<length>";
  inherits: false;
  initial-value: 0;
}

@property --tw-ring-offset-color {
  syntax: "*";
  inherits: false;
  initial-value: #fff;
}

@property --tw-ring-offset-shadow {
  syntax: "*";
  inherits: false;
  initial-value: 0 0 #0000;
}

@property --tw-outline-style {
  syntax: "*";
  inherits: false;
  initial-value: solid;
}

@property --tw-duration {
  syntax: "*";
  inherits: false
}

@property --tw-ease {
  syntax: "*";
  inherits: false
}
`;
