/* AUTO-GENERATED by scripts/gen-preview-css.mjs -- do not edit by hand.
 * Real Tailwind v4 output for Tabs's own classes, compiled against
 * tokens/kortix-tokens.css. Inlined because the preview sandbox runs
 * Tailwind v3 and cannot resolve Suna's v4 @theme tokens. */
export const PREVIEW_CSS = `/*! tailwindcss v4.3.3 | MIT License | https://tailwindcss.com */

  @supports (((-webkit-hyphens: none)) and (not (margin-trim: inline))) or ((-moz-orient: inline) and (not (color: rgb(from red r g b)))) {
    *, :before, :after, ::backdrop {
      --tw-space-y-reverse: 0;
      --tw-border-style: solid;
      --tw-font-weight: initial;
      --tw-shadow: 0 0 #0000;
      --tw-shadow-color: initial;
      --tw-shadow-alpha: 100%;
      --tw-inset-shadow: 0 0 #0000;
      --tw-inset-shadow-color: initial;
      --tw-inset-shadow-alpha: 100%;
      --tw-ring-color: initial;
      --tw-ring-shadow: 0 0 #0000;
      --tw-inset-ring-color: initial;
      --tw-inset-ring-shadow: 0 0 #0000;
      --tw-ring-inset: initial;
      --tw-ring-offset-width: 0px;
      --tw-ring-offset-color: #fff;
      --tw-ring-offset-shadow: 0 0 #0000;
      --tw-outline-style: solid;
      --tw-blur: initial;
      --tw-brightness: initial;
      --tw-contrast: initial;
      --tw-grayscale: initial;
      --tw-hue-rotate: initial;
      --tw-invert: initial;
      --tw-opacity: initial;
      --tw-saturate: initial;
      --tw-sepia: initial;
      --tw-drop-shadow: initial;
      --tw-drop-shadow-color: initial;
      --tw-drop-shadow-alpha: 100%;
      --tw-drop-shadow-size: initial;
      --tw-duration: initial;
      --tw-ease: initial;
      --tw-content: "";
    }
  }



  :root, :host {
    --spacing: .25rem;
    --font-weight-medium: 500;
    --default-transition-duration: .15s;
    --default-transition-timing-function: cubic-bezier(.4, 0, .2, 1);
    --default-font-family: var(--font-roobert);
    --default-mono-font-family: var(--font-roobert-mono);
    --color-ring: var(--ring);
  }



  *, :after, :before, ::backdrop {
    box-sizing: border-box;
    border: 0 solid;
    margin: 0;
    padding: 0;
  }

  ::file-selector-button {
    box-sizing: border-box;
    border: 0 solid;
    margin: 0;
    padding: 0;
  }

  html, :host {
    -webkit-text-size-adjust: 100%;
    tab-size: 4;
    line-height: 1.5;
    font-family: var(--default-font-family, -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, "Helvetica Neue", "Noto Sans", Arial, sans-serif, "Apple Color Emoji", "Segoe UI Emoji", "Segoe UI Symbol", "Noto Color Emoji");
    font-feature-settings: var(--default-font-feature-settings, normal);
    font-variation-settings: var(--default-font-variation-settings, normal);
    -webkit-tap-highlight-color: transparent;
  }

  hr {
    height: 0;
    color: inherit;
    border-top-width: 1px;
  }

  abbr:where([title]) {
    -webkit-text-decoration: underline dotted;
    text-decoration: underline dotted;
  }

  h1, h2, h3, h4, h5, h6 {
    font-size: inherit;
    font-weight: inherit;
  }

  a {
    color: inherit;
    -webkit-text-decoration: inherit;
    -webkit-text-decoration: inherit;
    -webkit-text-decoration: inherit;
    text-decoration: inherit;
  }

  b, strong {
    font-weight: bolder;
  }

  code, kbd, samp, pre {
    font-family: var(--default-mono-font-family, ui-monospace, SFMono-Regular, Menlo, Monaco, Consolas, "Liberation Mono", "Courier New", monospace);
    font-feature-settings: var(--default-mono-font-feature-settings, normal);
    font-variation-settings: var(--default-mono-font-variation-settings, normal);
    font-size: 1em;
  }

  small {
    font-size: 80%;
  }

  sub, sup {
    vertical-align: baseline;
    font-size: 75%;
    line-height: 0;
    position: relative;
  }

  sub {
    bottom: -.25em;
  }

  sup {
    top: -.5em;
  }

  table {
    text-indent: 0;
    border-color: inherit;
    border-collapse: collapse;
  }

  :-moz-focusring:where(:not(iframe)) {
    outline: auto;
  }

  progress {
    vertical-align: baseline;
  }

  summary {
    display: list-item;
  }

  ol, ul, menu {
    list-style: none;
  }

  img, svg, video, canvas, audio, iframe, embed, object {
    vertical-align: middle;
    display: block;
  }

  img, video {
    max-width: 100%;
    height: auto;
  }

  button, input, select, optgroup, textarea {
    font: inherit;
    font-feature-settings: inherit;
    font-variation-settings: inherit;
    letter-spacing: inherit;
    color: inherit;
    opacity: 1;
    background-color: #0000;
    border-radius: 0;
  }

  ::file-selector-button {
    font: inherit;
    font-feature-settings: inherit;
    font-variation-settings: inherit;
    letter-spacing: inherit;
    color: inherit;
    opacity: 1;
    background-color: #0000;
    border-radius: 0;
  }

  :where(select:is([multiple], [size])) optgroup {
    font-weight: bolder;
  }

  :where(select:is([multiple], [size])) optgroup option {
    padding-inline-start: 20px;
  }

  ::file-selector-button {
    margin-inline-end: 4px;
  }

  ::placeholder {
    opacity: 1;
  }

  @supports (not ((-webkit-appearance: -apple-pay-button))) or (contain-intrinsic-size: 1px) {
    ::placeholder {
      color: currentColor;
    }

    @supports (color: color-mix(in lab, red, red)) {
      ::placeholder {
        color: color-mix(in oklab, currentcolor 50%, transparent);
      }
    }
  }

  textarea {
    resize: vertical;
  }

  ::-webkit-search-decoration {
    -webkit-appearance: none;
  }

  ::-webkit-date-and-time-value {
    min-height: 1lh;
    text-align: inherit;
  }

  ::-webkit-datetime-edit {
    display: inline-flex;
  }

  ::-webkit-datetime-edit-fields-wrapper {
    padding: 0;
  }

  ::-webkit-datetime-edit {
    padding-block: 0;
  }

  ::-webkit-datetime-edit-year-field {
    padding-block: 0;
  }

  ::-webkit-datetime-edit-month-field {
    padding-block: 0;
  }

  ::-webkit-datetime-edit-day-field {
    padding-block: 0;
  }

  ::-webkit-datetime-edit-hour-field {
    padding-block: 0;
  }

  ::-webkit-datetime-edit-minute-field {
    padding-block: 0;
  }

  ::-webkit-datetime-edit-second-field {
    padding-block: 0;
  }

  ::-webkit-datetime-edit-millisecond-field {
    padding-block: 0;
  }

  ::-webkit-datetime-edit-meridiem-field {
    padding-block: 0;
  }

  ::-webkit-calendar-picker-indicator {
    line-height: 1;
  }

  :-moz-ui-invalid {
    box-shadow: none;
  }

  button, input:where([type="button"], [type="reset"], [type="submit"]) {
    appearance: button;
  }

  ::file-selector-button {
    appearance: button;
  }

  ::-webkit-inner-spin-button {
    height: auto;
  }

  ::-webkit-outer-spin-button {
    height: auto;
  }

  [hidden]:where(:not([hidden="until-found"])) {
    display: none !important;
  }

  :root {
    color-scheme: light;
  }

  .dark {
    color-scheme: dark;
  }





  .pointer-events-none {
    pointer-events: none;
  }

  .collapse {
    visibility: collapse;
  }

  .absolute {
    position: absolute;
  }

  .relative {
    position: relative;
  }

  .top-0 {
    top: 0;
  }

  .left-0 {
    left: 0;
  }

  .z-0 {
    z-index: 0;
  }

  .z-10 {
    z-index: 10;
  }

  .container {
    width: 100%;
  }

  @media (min-width: 40rem) {
    .container {
      max-width: 40rem;
    }
  }

  @media (min-width: 48rem) {
    .container {
      max-width: 48rem;
    }
  }

  @media (min-width: 64rem) {
    .container {
      max-width: 64rem;
    }
  }

  @media (min-width: 80rem) {
    .container {
      max-width: 80rem;
    }
  }

  @media (min-width: 96rem) {
    .container {
      max-width: 96rem;
    }
  }

  .flex {
    display: flex;
  }

  .inline-flex {
    display: inline-flex;
  }

  .h-6 {
    height: calc(var(--spacing) * 6);
  }

  .h-7 {
    height: calc(var(--spacing) * 7);
  }

  .h-8 {
    height: calc(var(--spacing) * 8);
  }

  .h-9 {
    height: calc(var(--spacing) * 9);
  }

  .h-10 {
    height: calc(var(--spacing) * 10);
  }

  .h-\\[calc\\(100\\%-4px\\)\\] {
    height: calc(100% - 4px);
  }

  .h-auto {
    height: auto;
  }

  .h-full {
    height: 100%;
  }

  .w-fit {
    width: fit-content;
  }

  .w-full {
    width: 100%;
  }

  .min-w-0 {
    min-width: 0;
  }

  .flex-1 {
    flex: 1;
  }

  .shrink-0 {
    flex-shrink: 0;
  }

  .cursor-pointer {
    cursor: pointer;
  }

  .resize {
    resize: both;
  }

  .flex-col {
    flex-direction: column;
  }

  .items-center {
    align-items: center;
  }

  .items-stretch {
    align-items: stretch;
  }

  .justify-between {
    justify-content: space-between;
  }

  .justify-center {
    justify-content: center;
  }

  .justify-start {
    justify-content: flex-start;
  }

  .gap-0 {
    gap: 0;
  }

  .gap-0\\.5 {
    gap: calc(var(--spacing) * .5);
  }

  .gap-1 {
    gap: var(--spacing);
  }

  .gap-1\\.5 {
    gap: calc(var(--spacing) * 1.5);
  }

  .gap-2 {
    gap: calc(var(--spacing) * 2);
  }

  .gap-4 {
    gap: calc(var(--spacing) * 4);
  }

  :where(.space-y-3 > :not(:last-child)) {
    --tw-space-y-reverse: 0;
    margin-block-start: calc(calc(var(--spacing) * 3) * var(--tw-space-y-reverse));
    margin-block-end: calc(calc(var(--spacing) * 3) * calc(1 - var(--tw-space-y-reverse)));
  }

  :where(.space-y-8 > :not(:last-child)) {
    --tw-space-y-reverse: 0;
    margin-block-start: calc(calc(var(--spacing) * 8) * var(--tw-space-y-reverse));
    margin-block-end: calc(calc(var(--spacing) * 8) * calc(1 - var(--tw-space-y-reverse)));
  }

  .truncate {
    text-overflow: ellipsis;
    white-space: nowrap;
    overflow: hidden;
  }

  .rounded-\\[calc\\(var\\(--radius\\)-2\\.5px\\)\\] {
    border-radius: calc(var(--radius) - 2.5px);
  }

  .rounded-\\[calc\\(var\\(--radius\\)-3px\\)\\] {
    border-radius: calc(var(--radius) - 3px);
  }

  .rounded-none {
    border-radius: 0;
  }

  .rounded-sm {
    border-radius: calc(var(--radius) - 4px);
  }

  .border {
    border-style: var(--tw-border-style);
    border-width: 1px;
  }

  .border-b {
    border-bottom-style: var(--tw-border-style);
    border-bottom-width: 1px;
  }

  .border-border, .border-border\\/60 {
    border-color: var(--border);
  }

  @supports (color: color-mix(in lab, red, red)) {
    .border-border\\/60 {
      border-color: color-mix(in oklab, var(--border) 60%, transparent);
    }
  }

  .border-transparent {
    border-color: #0000;
  }

  .bg-background {
    background-color: var(--background);
  }

  .bg-foreground\\/5 {
    background-color: var(--foreground);
  }

  @supports (color: color-mix(in lab, red, red)) {
    .bg-foreground\\/5 {
      background-color: color-mix(in oklab, var(--foreground) 5%, transparent);
    }
  }

  .bg-input {
    background-color: var(--input);
  }

  .bg-transparent {
    background-color: #0000;
  }

  .p-0 {
    padding: 0;
  }

  .p-0\\.5 {
    padding: calc(var(--spacing) * .5);
  }

  .p-6 {
    padding: calc(var(--spacing) * 6);
  }

  .px-2\\.5 {
    padding-inline: calc(var(--spacing) * 2.5);
  }

  .px-3 {
    padding-inline: calc(var(--spacing) * 3);
  }

  .px-4 {
    padding-inline: calc(var(--spacing) * 4);
  }

  .px-5 {
    padding-inline: calc(var(--spacing) * 5);
  }

  .px-6 {
    padding-inline: calc(var(--spacing) * 6);
  }

  .py-1\\.5 {
    padding-block: calc(var(--spacing) * 1.5);
  }

  .py-2 {
    padding-block: calc(var(--spacing) * 2);
  }

  .pt-3 {
    padding-top: calc(var(--spacing) * 3);
  }

  .text-left {
    text-align: left;
  }

  .font-mono {
    font-family: var(--font-roobert-mono);
  }

  .font-sans {
    font-family: var(--font-roobert);
  }

  .text-sm {
    font-size: .875rem;
    line-height: var(--tw-leading, calc(1.25 / .875));
  }

  .text-xs {
    font-size: .8125rem;
    line-height: var(--tw-leading, calc(1 / .8125));
  }

  .font-medium {
    --tw-font-weight: var(--font-weight-medium);
    font-weight: var(--font-weight-medium);
  }

  .whitespace-nowrap {
    white-space: nowrap;
  }

  .text-foreground {
    color: var(--foreground);
  }

  .text-kortix-blue {
    color: var(--kortix-blue);
  }

  .text-kortix-green {
    color: var(--kortix-green);
  }

  .text-kortix-red {
    color: var(--kortix-red);
  }

  .text-kortix-yellow {
    color: var(--kortix-yellow);
  }

  .text-muted-foreground, .text-muted-foreground\\/60 {
    color: var(--muted-foreground);
  }

  @supports (color: color-mix(in lab, red, red)) {
    .text-muted-foreground\\/60 {
      color: color-mix(in oklab, var(--muted-foreground) 60%, transparent);
    }
  }

  .underline {
    text-decoration-line: underline;
  }

  .shadow-none {
    --tw-shadow: 0 0 #0000;
    box-shadow: var(--tw-inset-shadow), var(--tw-inset-ring-shadow), var(--tw-ring-offset-shadow), var(--tw-ring-shadow), var(--tw-shadow);
  }

  .outline {
    outline-style: var(--tw-outline-style);
    outline-width: 1px;
  }

  .filter {
    filter: var(--tw-blur, ) var(--tw-brightness, ) var(--tw-contrast, ) var(--tw-grayscale, ) var(--tw-hue-rotate, ) var(--tw-invert, ) var(--tw-saturate, ) var(--tw-sepia, ) var(--tw-drop-shadow, );
  }

  .transition {
    transition-property: color, background-color, border-color, outline-color, text-decoration-color, fill, stroke, --tw-gradient-from, --tw-gradient-via, --tw-gradient-to, opacity, box-shadow, transform, translate, scale, rotate, filter, -webkit-backdrop-filter, backdrop-filter, display, content-visibility, overlay, pointer-events;
    transition-timing-function: var(--tw-ease, var(--default-transition-timing-function));
    transition-duration: var(--tw-duration, var(--default-transition-duration));
  }

  .transition-\\[color\\,background-color\\,border-color\\,box-shadow\\] {
    transition-property: color, background-color, border-color, box-shadow;
    transition-timing-function: var(--tw-ease, var(--default-transition-timing-function));
    transition-duration: var(--tw-duration, var(--default-transition-duration));
  }

  .transition-\\[color\\,background-color\\,border-color\\] {
    transition-property: color, background-color, border-color;
    transition-timing-function: var(--tw-ease, var(--default-transition-timing-function));
    transition-duration: var(--tw-duration, var(--default-transition-duration));
  }

  .transition-colors {
    transition-property: color, background-color, border-color, outline-color, text-decoration-color, fill, stroke, --tw-gradient-from, --tw-gradient-via, --tw-gradient-to;
    transition-timing-function: var(--tw-ease, var(--default-transition-timing-function));
    transition-duration: var(--tw-duration, var(--default-transition-duration));
  }

  .duration-150 {
    --tw-duration: .15s;
    transition-duration: .15s;
  }

  .ease-default {
    --tw-ease: cubic-bezier(.2, 0, 0, 1);
    transition-timing-function: cubic-bezier(.2, 0, 0, 1);
  }

  .outline-none {
    --tw-outline-style: none;
    outline-style: none;
  }

  .last\\:border-b-0:last-child {
    border-bottom-style: var(--tw-border-style);
    border-bottom-width: 0;
  }

  @media (hover: hover) {
    .hover\\:text-foreground\\/80:hover {
      color: var(--foreground);
    }

    @supports (color: color-mix(in lab, red, red)) {
      .hover\\:text-foreground\\/80:hover {
        color: color-mix(in oklab, var(--foreground) 80%, transparent);
      }
    }
  }

  .focus-visible\\:ring-\\[0\\.6px\\]:focus-visible {
    --tw-ring-shadow: var(--tw-ring-inset, ) 0 0 0 calc(.6px + var(--tw-ring-offset-width)) var(--tw-ring-color, currentcolor);
    box-shadow: var(--tw-inset-shadow), var(--tw-inset-ring-shadow), var(--tw-ring-offset-shadow), var(--tw-ring-shadow), var(--tw-shadow);
  }

  .focus-visible\\:ring-kortix-blue:focus-visible {
    --tw-ring-color: var(--kortix-blue);
  }

  .focus-visible\\:outline-none:focus-visible {
    --tw-outline-style: none;
    outline-style: none;
  }

  .disabled\\:pointer-events-none:disabled {
    pointer-events: none;
  }

  .disabled\\:opacity-50:disabled {
    opacity: .5;
  }

  .has-\\[\\>svg\\]\\:px-2:has( > svg) {
    padding-inline: calc(var(--spacing) * 2);
  }

  .has-\\[\\>svg\\]\\:px-2\\.5:has( > svg) {
    padding-inline: calc(var(--spacing) * 2.5);
  }

  .has-\\[\\>svg\\]\\:px-3:has( > svg) {
    padding-inline: calc(var(--spacing) * 3);
  }

  .has-\\[\\>svg\\]\\:px-4:has( > svg) {
    padding-inline: calc(var(--spacing) * 4);
  }

  :is(.\\*\\*\\:data-\\[slot\\=tabs-trigger\\]\\:relative *)[data-slot="tabs-trigger"] {
    position: relative;
  }

  :is(.\\*\\*\\:data-\\[slot\\=tabs-trigger\\]\\:h-full *)[data-slot="tabs-trigger"] {
    height: 100%;
  }

  :is(.\\*\\*\\:data-\\[slot\\=tabs-trigger\\]\\:rounded-none *)[data-slot="tabs-trigger"] {
    border-radius: 0;
  }

  :is(.\\*\\*\\:data-\\[slot\\=tabs-trigger\\]\\:border-0 *)[data-slot="tabs-trigger"] {
    border-style: var(--tw-border-style);
    border-width: 0;
  }

  :is(.\\*\\*\\:data-\\[slot\\=tabs-trigger\\]\\:bg-transparent *)[data-slot="tabs-trigger"] {
    background-color: #0000;
  }

  :is(.\\*\\*\\:data-\\[slot\\=tabs-trigger\\]\\:shadow-none *)[data-slot="tabs-trigger"] {
    --tw-shadow: 0 0 #0000;
    box-shadow: var(--tw-inset-shadow), var(--tw-inset-ring-shadow), var(--tw-ring-offset-shadow), var(--tw-ring-shadow), var(--tw-shadow);
  }

  :is(.\\*\\*\\:data-\\[slot\\=tabs-trigger\\]\\:after\\:pointer-events-none *)[data-slot="tabs-trigger"]:after {
    content: var(--tw-content);
    pointer-events: none;
  }

  :is(.\\*\\*\\:data-\\[slot\\=tabs-trigger\\]\\:after\\:absolute *)[data-slot="tabs-trigger"]:after {
    content: var(--tw-content);
    position: absolute;
  }

  :is(.\\*\\*\\:data-\\[slot\\=tabs-trigger\\]\\:after\\:inset-x-0 *)[data-slot="tabs-trigger"]:after {
    content: var(--tw-content);
    inset-inline: 0;
  }

  :is(.\\*\\*\\:data-\\[slot\\=tabs-trigger\\]\\:after\\:bottom-0 *)[data-slot="tabs-trigger"]:after {
    content: var(--tw-content);
    bottom: 0;
  }

  :is(.\\*\\*\\:data-\\[slot\\=tabs-trigger\\]\\:after\\:h-0\\.5 *)[data-slot="tabs-trigger"]:after {
    content: var(--tw-content);
    height: calc(var(--spacing) * .5);
  }

  :is(.\\*\\*\\:data-\\[slot\\=tabs-trigger\\]\\:after\\:h-\\[1\\.5px\\] *)[data-slot="tabs-trigger"]:after {
    content: var(--tw-content);
    height: 1.5px;
  }

  :is(.\\*\\*\\:data-\\[slot\\=tabs-trigger\\]\\:after\\:h-\\[3px\\] *)[data-slot="tabs-trigger"]:after {
    content: var(--tw-content);
    height: 3px;
  }

  :is(.\\*\\*\\:data-\\[slot\\=tabs-trigger\\]\\:after\\:h-px *)[data-slot="tabs-trigger"]:after {
    content: var(--tw-content);
    height: 1px;
  }

  :is(.\\*\\*\\:data-\\[slot\\=tabs-trigger\\]\\:after\\:rounded-full *)[data-slot="tabs-trigger"]:after {
    content: var(--tw-content);
    border-radius: 3.40282e38px;
  }

  :is(.\\*\\*\\:data-\\[slot\\=tabs-trigger\\]\\:after\\:bg-transparent *)[data-slot="tabs-trigger"]:after {
    content: var(--tw-content);
    background-color: #0000;
  }

  :is(.\\*\\*\\:data-\\[slot\\=tabs-trigger\\]\\:after\\:content-\\[\\'\\'\\] *)[data-slot="tabs-trigger"]:after {
    --tw-content: "";
    content: var(--tw-content);
  }

  .data-\\[state\\=active\\]\\:border-border[data-state="active"] {
    border-color: var(--border);
  }

  .data-\\[state\\=active\\]\\:bg-background[data-state="active"] {
    background-color: var(--background);
  }

  .data-\\[state\\=active\\]\\:bg-input[data-state="active"] {
    background-color: var(--input);
  }

  .data-\\[state\\=active\\]\\:bg-transparent[data-state="active"] {
    background-color: #0000;
  }

  .data-\\[state\\=active\\]\\:text-foreground[data-state="active"] {
    color: var(--foreground);
  }

  .data-\\[state\\=active\\]\\:shadow-none[data-state="active"] {
    --tw-shadow: 0 0 #0000;
    box-shadow: var(--tw-inset-shadow), var(--tw-inset-ring-shadow), var(--tw-ring-offset-shadow), var(--tw-ring-shadow), var(--tw-shadow);
  }

  .data-\\[state\\=active\\]\\:shadow-sm[data-state="active"] {
    --tw-shadow: 0 1px 2px 0 var(--tw-shadow-color, light-dark(oklch(0% 0 0 / .04), oklch(0% 0 0 / .2))), 0 2px 4px -1px var(--tw-shadow-color, light-dark(oklch(0% 0 0 / .03), oklch(0% 0 0 / .16))), 0 0 6px 0 var(--tw-shadow-color, light-dark(oklch(0% 0 0 / .03), oklch(0% 0 0 / .12)));
    box-shadow: var(--tw-inset-shadow), var(--tw-inset-ring-shadow), var(--tw-ring-offset-shadow), var(--tw-ring-shadow), var(--tw-shadow);
  }

  .data-\\[state\\=active\\]\\:ring-1[data-state="active"] {
    --tw-ring-shadow: var(--tw-ring-inset, ) 0 0 0 calc(1px + var(--tw-ring-offset-width)) var(--tw-ring-color, currentcolor);
    box-shadow: var(--tw-inset-shadow), var(--tw-inset-ring-shadow), var(--tw-ring-offset-shadow), var(--tw-ring-shadow), var(--tw-shadow);
  }

  .data-\\[state\\=active\\]\\:ring-foreground\\/6[data-state="active"] {
    --tw-ring-color: var(--foreground);
  }

  @supports (color: color-mix(in lab, red, red)) {
    .data-\\[state\\=active\\]\\:ring-foreground\\/6[data-state="active"] {
      --tw-ring-color: color-mix(in oklab, var(--foreground) 6%, transparent);
    }
  }

  :is(.\\*\\*\\:data-\\[slot\\=tabs-trigger\\]\\:data-\\[state\\=active\\]\\:bg-transparent *)[data-slot="tabs-trigger"][data-state="active"] {
    background-color: #0000;
  }

  :is(.\\*\\*\\:data-\\[slot\\=tabs-trigger\\]\\:data-\\[state\\=active\\]\\:text-foreground *)[data-slot="tabs-trigger"][data-state="active"] {
    color: var(--foreground);
  }

  :is(.\\*\\*\\:data-\\[slot\\=tabs-trigger\\]\\:data-\\[state\\=active\\]\\:shadow-none *)[data-slot="tabs-trigger"][data-state="active"] {
    --tw-shadow: 0 0 #0000;
    box-shadow: var(--tw-inset-shadow), var(--tw-inset-ring-shadow), var(--tw-ring-offset-shadow), var(--tw-ring-shadow), var(--tw-shadow);
  }

  :is(.\\*\\*\\:data-\\[slot\\=tabs-trigger\\]\\:data-\\[state\\=active\\]\\:after\\:bg-foreground *)[data-slot="tabs-trigger"][data-state="active"]:after {
    content: var(--tw-content);
    background-color: var(--foreground);
  }

  .data-\\[state\\=inactive\\]\\:bg-transparent[data-state="inactive"] {
    background-color: #0000;
  }

  .data-\\[state\\=inactive\\]\\:text-muted-foreground[data-state="inactive"] {
    color: var(--muted-foreground);
  }

  @media (hover: hover) {
    .hover\\:data-\\[state\\=inactive\\]\\:bg-foreground\\/5:hover[data-state="inactive"] {
      background-color: var(--foreground);
    }

    @supports (color: color-mix(in lab, red, red)) {
      .hover\\:data-\\[state\\=inactive\\]\\:bg-foreground\\/5:hover[data-state="inactive"] {
        background-color: color-mix(in oklab, var(--foreground) 5%, transparent);
      }
    }

    .hover\\:data-\\[state\\=inactive\\]\\:text-foreground:hover[data-state="inactive"] {
      color: var(--foreground);
    }
  }

  :is(.\\*\\*\\:data-\\[slot\\=tabs-trigger\\]\\:data-\\[state\\=inactive\\]\\:bg-transparent *)[data-slot="tabs-trigger"][data-state="inactive"] {
    background-color: #0000;
  }

  :is(.\\*\\*\\:data-\\[slot\\=tabs-trigger\\]\\:data-\\[state\\=inactive\\]\\:text-muted-foreground *)[data-slot="tabs-trigger"][data-state="inactive"] {
    color: var(--muted-foreground);
  }

  @media (prefers-reduced-motion: reduce) {
    .motion-reduce\\:transition-none {
      transition-property: none;
    }
  }

  .\\[\\&_svg\\]\\:pointer-events-none svg {
    pointer-events: none;
  }

  .\\[\\&_svg\\]\\:shrink-0 svg {
    flex-shrink: 0;
  }

  .\\[\\&_svg\\:not\\(\\[class\\*\\=\\'size-\\'\\]\\)\\]\\:size-3\\.5 svg:not([class*="size-"]) {
    width: calc(var(--spacing) * 3.5);
    height: calc(var(--spacing) * 3.5);
  }

  .\\[\\&_svg\\:not\\(\\[class\\*\\=\\'size-\\'\\]\\)\\]\\:size-4 svg:not([class*="size-"]) {
    width: calc(var(--spacing) * 4);
    height: calc(var(--spacing) * 4);
  }


:root {
  --background: oklch(100% 0 0);
  --pane: oklch(100% 0 0);
  --foreground: oklch(0% 0 0);
  --foreground-strong: var(--foreground);
  --foreground-weak: var(--muted-foreground);
  --card: oklch(96.72% 0 0);
  --card-foreground: oklch(0% 0 0);
  --popover: oklch(100% 0 0);
  --popover-foreground: oklch(0% 0 0);
  --primary: oklch(0% 0 0);
  --primary-foreground: oklch(100% 0 0);
  --secondary: oklch(94.31% 0 0);
  --secondary-foreground: oklch(0% 0 0);
  --muted: oklch(94.31% 0 0);
  --muted-foreground: oklch(51.03% 0 0);
  --accent: oklch(96.72% 0 0);
  --accent-foreground: oklch(0% 0 0);
  --destructive: oklch(58.3% .2387 28.4765);
  --destructive-foreground: oklch(98.51% 0 0);
  --border: oklch(91.28% 0 0);
  --input: oklch(94.31% 0 0);
  --ring: oklch(66.9% .1837 248.807);
  --hover: oklch(0% 0 0 / .045);
  --active: oklch(0% 0 0 / .075);
  --focus-ring: var(--ring);
  --chart-1: oklch(87.81% .1688 91.8567);
  --chart-2: oklch(77.24% .1728 65.367);
  --chart-3: oklch(66.71% .1685 53.3814);
  --chart-4: oklch(55.7% .1583 45.3594);
  --chart-5: oklch(47.47% .1358 44.9806);
  --sidebar: oklch(96.72% 0 0);
  --sidebar-foreground: oklch(0% 0 0);
  --sidebar-primary: oklch(66.9% .1837 248.807);
  --sidebar-primary-foreground: oklch(100% 0 0);
  --sidebar-accent: oklch(94.31% 0 0);
  --sidebar-accent-foreground: oklch(0% 0 0);
  --sidebar-border: oklch(91.28% 0 0);
  --sidebar-ring: oklch(66.9% .1837 248.807);
  --radius: .625rem;
  --tracking-normal: 0em;
  --spacing: .23rem;
  --kortix-base: var(--color-ring);
  --kortix-blue: oklch(65.2% .177 252.624);
  --kortix-yellow: oklch(73.2% .15 90.688);
  --kortix-orange: oklch(69.1% .142 71.784);
  --kortix-green: oklch(58.1% .165 146.619);
  --kortix-purple: oklch(67.5% .131 306.212);
  --kortix-red: oklch(64.8% .202 24.745);
  --duration-fast: .1s;
  --duration-normal: .15s;
  --duration-moderate: .2s;
  --duration-slow: .3s;
  --duration-slower: .5s;
  --ease-default: cubic-bezier(.2, 0, 0, 1);
  --ease-in: cubic-bezier(.4, 0, 1, 1);
  --ease-out: cubic-bezier(0, 0, .2, 1);
  --ease-in-out: cubic-bezier(.4, 0, .2, 1);
}

.dark {
  --background: oklch(17% 0 0);
  --pane: oklch(15.43% 0 0);
  --foreground: oklch(100% 0 0);
  --foreground-strong: var(--foreground);
  --foreground-weak: var(--muted-foreground);
  --card: oklch(19.13% 0 0);
  --card-foreground: oklch(100% 0 0);
  --popover: oklch(19.13% 0 0);
  --popover-foreground: oklch(100% 0 0);
  --primary: oklch(100% 0 0);
  --primary-foreground: oklch(13.98% 0 0);
  --secondary: oklch(22.64% 0 0);
  --secondary-foreground: oklch(100% 0 0);
  --muted: oklch(22.64% 0 0);
  --muted-foreground: oklch(68.3% 0 0);
  --accent: oklch(19.13% 0 0);
  --accent-foreground: oklch(100% 0 0);
  --destructive: oklch(70.22% .1892 22.2279);
  --destructive-foreground: oklch(98.51% 0 0);
  --border: oklch(26.86% 0 0);
  --input: oklch(22.64% 0 0);
  --ring: oklch(66.9% .1837 248.807);
  --hover: oklch(100% 0 0 / .06);
  --active: oklch(100% 0 0 / .1);
  --focus-ring: var(--ring);
  --chart-1: oklch(87.81% .1688 91.8567);
  --chart-2: oklch(77.24% .1728 65.367);
  --chart-3: oklch(66.71% .1685 53.3814);
  --chart-4: oklch(55.7% .1583 45.3594);
  --chart-5: oklch(47.47% .1358 44.9806);
  --sidebar: oklch(19.13% 0 0);
  --sidebar-foreground: oklch(100% 0 0);
  --sidebar-primary: oklch(66.9% .1837 248.807);
  --sidebar-primary-foreground: oklch(100% 0 0);
  --sidebar-accent: oklch(22.64% 0 0);
  --sidebar-accent-foreground: oklch(100% 0 0);
  --sidebar-border: oklch(21.78% 0 0);
  --sidebar-ring: oklch(66.9% .1837 248.807);
  --radius: .625rem;
  --kortix-base: var(--color-ring);
  --kortix-blue: oklch(65.2% .177 252.624);
  --kortix-yellow: oklch(73.2% .15 90.688);
  --kortix-orange: oklch(69.1% .142 71.784);
  --kortix-green: oklch(58.1% .165 146.619);
  --kortix-purple: oklch(67.5% .131 306.212);
  --kortix-red: oklch(64.8% .202 24.745);
}

@keyframes spinner-orbit {
  to {
    transform: rotate(360deg);
  }
}

@keyframes spinner-spin {
  to {
    transform: rotate(360deg);
  }
}

@keyframes spinner-dash {
  0% {
    stroke-dashoffset: 58px;
    transform: rotate(0);
  }

  50% {
    stroke-dashoffset: 14px;
    transform: rotate(180deg);
  }

  100% {
    stroke-dashoffset: 58px;
    transform: rotate(360deg);
  }
}

.animate-spinner-orbit {
  transform-origin: center;
  animation: 1.4s linear infinite spinner-orbit;
}

.animate-spinner-spin {
  transform-origin: center;
  animation: 1s linear infinite spinner-spin;
}

.animate-spinner-dash {
  transform-origin: center;
  transform-box: fill-box;
  stroke-dasharray: 62.83;
  animation: 1.4s cubic-bezier(.77, 0, .175, 1) infinite spinner-dash;
}

@keyframes spinner-spokes {
  to {
    transform: rotate(360deg);
  }
}

.animate-spinner-spokes {
  transform-origin: center;
  animation: .8s steps(8, end) infinite spinner-spokes;
}

@media (prefers-reduced-motion: reduce) {
  .animate-spinner-orbit, .animate-spinner-spin {
    animation: 1.4s linear infinite spinner-orbit;
  }

  .animate-spinner-dash {
    stroke-dashoffset: 34px;
    animation: none;
    transform: none;
  }

  .animate-spinner-spokes {
    animation: 1.4s linear infinite spinner-spokes;
  }
}

@property --tw-space-y-reverse {
  syntax: "*";
  inherits: false;
  initial-value: 0;
}

@property --tw-border-style {
  syntax: "*";
  inherits: false;
  initial-value: solid;
}

@property --tw-font-weight {
  syntax: "*";
  inherits: false
}

@property --tw-shadow {
  syntax: "*";
  inherits: false;
  initial-value: 0 0 #0000;
}

@property --tw-shadow-color {
  syntax: "*";
  inherits: false
}

@property --tw-shadow-alpha {
  syntax: "<percentage>";
  inherits: false;
  initial-value: 100%;
}

@property --tw-inset-shadow {
  syntax: "*";
  inherits: false;
  initial-value: 0 0 #0000;
}

@property --tw-inset-shadow-color {
  syntax: "*";
  inherits: false
}

@property --tw-inset-shadow-alpha {
  syntax: "<percentage>";
  inherits: false;
  initial-value: 100%;
}

@property --tw-ring-color {
  syntax: "*";
  inherits: false
}

@property --tw-ring-shadow {
  syntax: "*";
  inherits: false;
  initial-value: 0 0 #0000;
}

@property --tw-inset-ring-color {
  syntax: "*";
  inherits: false
}

@property --tw-inset-ring-shadow {
  syntax: "*";
  inherits: false;
  initial-value: 0 0 #0000;
}

@property --tw-ring-inset {
  syntax: "*";
  inherits: false
}

@property --tw-ring-offset-width {
  syntax: "<length>";
  inherits: false;
  initial-value: 0;
}

@property --tw-ring-offset-color {
  syntax: "*";
  inherits: false;
  initial-value: #fff;
}

@property --tw-ring-offset-shadow {
  syntax: "*";
  inherits: false;
  initial-value: 0 0 #0000;
}

@property --tw-outline-style {
  syntax: "*";
  inherits: false;
  initial-value: solid;
}

@property --tw-blur {
  syntax: "*";
  inherits: false
}

@property --tw-brightness {
  syntax: "*";
  inherits: false
}

@property --tw-contrast {
  syntax: "*";
  inherits: false
}

@property --tw-grayscale {
  syntax: "*";
  inherits: false
}

@property --tw-hue-rotate {
  syntax: "*";
  inherits: false
}

@property --tw-invert {
  syntax: "*";
  inherits: false
}

@property --tw-opacity {
  syntax: "*";
  inherits: false
}

@property --tw-saturate {
  syntax: "*";
  inherits: false
}

@property --tw-sepia {
  syntax: "*";
  inherits: false
}

@property --tw-drop-shadow {
  syntax: "*";
  inherits: false
}

@property --tw-drop-shadow-color {
  syntax: "*";
  inherits: false
}

@property --tw-drop-shadow-alpha {
  syntax: "<percentage>";
  inherits: false;
  initial-value: 100%;
}

@property --tw-drop-shadow-size {
  syntax: "*";
  inherits: false
}

@property --tw-duration {
  syntax: "*";
  inherits: false
}

@property --tw-ease {
  syntax: "*";
  inherits: false
}

@property --tw-content {
  syntax: "*";
  inherits: false;
  initial-value: "";
}
`;
