/* AUTO-GENERATED by scripts/gen-preview-css.mjs -- do not edit by hand.
 * Real Tailwind v4 output for Field's own classes, compiled against
 * tokens/kortix-tokens.css. Inlined because the preview sandbox runs
 * Tailwind v3 and cannot resolve Suna's v4 @theme tokens. */
export const PREVIEW_CSS = `/*! tailwindcss v4.3.3 | MIT License | https://tailwindcss.com */

  @supports (((-webkit-hyphens: none)) and (not (margin-trim: inline))) or ((-moz-orient: inline) and (not (color: rgb(from red r g b)))) {
    *, :before, :after, ::backdrop {
      --tw-border-style: solid;
      --tw-leading: initial;
      --tw-font-weight: initial;
      --tw-outline-style: solid;
    }
  }



  :root, :host {
    --spacing: .25rem;
    --container-xl: 36rem;
    --font-weight-normal: 400;
    --font-weight-medium: 500;
    --leading-snug: 1.375;
    --leading-normal: 1.5;
    --ease-in-out: cubic-bezier(.4, 0, .2, 1);
    --default-transition-duration: .15s;
    --default-transition-timing-function: cubic-bezier(.4, 0, .2, 1);
    --default-font-family: var(--font-roobert);
    --default-mono-font-family: var(--font-roobert-mono);
    --color-ring: var(--ring);
  }



  *, :after, :before, ::backdrop {
    box-sizing: border-box;
    border: 0 solid;
    margin: 0;
    padding: 0;
  }

  ::file-selector-button {
    box-sizing: border-box;
    border: 0 solid;
    margin: 0;
    padding: 0;
  }

  html, :host {
    -webkit-text-size-adjust: 100%;
    tab-size: 4;
    line-height: 1.5;
    font-family: var(--default-font-family, -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, "Helvetica Neue", "Noto Sans", Arial, sans-serif, "Apple Color Emoji", "Segoe UI Emoji", "Segoe UI Symbol", "Noto Color Emoji");
    font-feature-settings: var(--default-font-feature-settings, normal);
    font-variation-settings: var(--default-font-variation-settings, normal);
    -webkit-tap-highlight-color: transparent;
  }

  hr {
    height: 0;
    color: inherit;
    border-top-width: 1px;
  }

  abbr:where([title]) {
    -webkit-text-decoration: underline dotted;
    text-decoration: underline dotted;
  }

  h1, h2, h3, h4, h5, h6 {
    font-size: inherit;
    font-weight: inherit;
  }

  a {
    color: inherit;
    -webkit-text-decoration: inherit;
    -webkit-text-decoration: inherit;
    -webkit-text-decoration: inherit;
    text-decoration: inherit;
  }

  b, strong {
    font-weight: bolder;
  }

  code, kbd, samp, pre {
    font-family: var(--default-mono-font-family, ui-monospace, SFMono-Regular, Menlo, Monaco, Consolas, "Liberation Mono", "Courier New", monospace);
    font-feature-settings: var(--default-mono-font-feature-settings, normal);
    font-variation-settings: var(--default-mono-font-variation-settings, normal);
    font-size: 1em;
  }

  small {
    font-size: 80%;
  }

  sub, sup {
    vertical-align: baseline;
    font-size: 75%;
    line-height: 0;
    position: relative;
  }

  sub {
    bottom: -.25em;
  }

  sup {
    top: -.5em;
  }

  table {
    text-indent: 0;
    border-color: inherit;
    border-collapse: collapse;
  }

  :-moz-focusring:where(:not(iframe)) {
    outline: auto;
  }

  progress {
    vertical-align: baseline;
  }

  summary {
    display: list-item;
  }

  ol, ul, menu {
    list-style: none;
  }

  img, svg, video, canvas, audio, iframe, embed, object {
    vertical-align: middle;
    display: block;
  }

  img, video {
    max-width: 100%;
    height: auto;
  }

  button, input, select, optgroup, textarea {
    font: inherit;
    font-feature-settings: inherit;
    font-variation-settings: inherit;
    letter-spacing: inherit;
    color: inherit;
    opacity: 1;
    background-color: #0000;
    border-radius: 0;
  }

  ::file-selector-button {
    font: inherit;
    font-feature-settings: inherit;
    font-variation-settings: inherit;
    letter-spacing: inherit;
    color: inherit;
    opacity: 1;
    background-color: #0000;
    border-radius: 0;
  }

  :where(select:is([multiple], [size])) optgroup {
    font-weight: bolder;
  }

  :where(select:is([multiple], [size])) optgroup option {
    padding-inline-start: 20px;
  }

  ::file-selector-button {
    margin-inline-end: 4px;
  }

  ::placeholder {
    opacity: 1;
  }

  @supports (not ((-webkit-appearance: -apple-pay-button))) or (contain-intrinsic-size: 1px) {
    ::placeholder {
      color: currentColor;
    }

    @supports (color: color-mix(in lab, red, red)) {
      ::placeholder {
        color: color-mix(in oklab, currentcolor 50%, transparent);
      }
    }
  }

  textarea {
    resize: vertical;
  }

  ::-webkit-search-decoration {
    -webkit-appearance: none;
  }

  ::-webkit-date-and-time-value {
    min-height: 1lh;
    text-align: inherit;
  }

  ::-webkit-datetime-edit {
    display: inline-flex;
  }

  ::-webkit-datetime-edit-fields-wrapper {
    padding: 0;
  }

  ::-webkit-datetime-edit {
    padding-block: 0;
  }

  ::-webkit-datetime-edit-year-field {
    padding-block: 0;
  }

  ::-webkit-datetime-edit-month-field {
    padding-block: 0;
  }

  ::-webkit-datetime-edit-day-field {
    padding-block: 0;
  }

  ::-webkit-datetime-edit-hour-field {
    padding-block: 0;
  }

  ::-webkit-datetime-edit-minute-field {
    padding-block: 0;
  }

  ::-webkit-datetime-edit-second-field {
    padding-block: 0;
  }

  ::-webkit-datetime-edit-millisecond-field {
    padding-block: 0;
  }

  ::-webkit-datetime-edit-meridiem-field {
    padding-block: 0;
  }

  ::-webkit-calendar-picker-indicator {
    line-height: 1;
  }

  :-moz-ui-invalid {
    box-shadow: none;
  }

  button, input:where([type="button"], [type="reset"], [type="submit"]) {
    appearance: button;
  }

  ::file-selector-button {
    appearance: button;
  }

  ::-webkit-inner-spin-button {
    height: auto;
  }

  ::-webkit-outer-spin-button {
    height: auto;
  }

  [hidden]:where(:not([hidden="until-found"])) {
    display: none !important;
  }

  :root {
    color-scheme: light;
  }

  .dark {
    color-scheme: dark;
  }





  .\\@container\\/field-group {
    container: field-group / inline-size;
  }

  .absolute {
    position: absolute;
  }

  .relative {
    position: relative;
  }

  .inset-0 {
    inset: 0;
  }

  .top-1\\/2 {
    top: 50%;
  }

  .mx-auto {
    margin-inline: auto;
  }

  .-my-2 {
    margin-block: calc(var(--spacing) * -2);
  }

  .mb-3 {
    margin-bottom: calc(var(--spacing) * 3);
  }

  .ml-4 {
    margin-left: calc(var(--spacing) * 4);
  }

  .block {
    display: block;
  }

  .flex {
    display: flex;
  }

  .size-4 {
    width: calc(var(--spacing) * 4);
    height: calc(var(--spacing) * 4);
  }

  .h-5 {
    height: calc(var(--spacing) * 5);
  }

  .h-8 {
    height: calc(var(--spacing) * 8);
  }

  .h-9 {
    height: calc(var(--spacing) * 9);
  }

  .h-10 {
    height: calc(var(--spacing) * 10);
  }

  .h-11 {
    height: calc(var(--spacing) * 11);
  }

  .h-12 {
    height: calc(var(--spacing) * 12);
  }

  .w-fit {
    width: fit-content;
  }

  .w-full {
    width: 100%;
  }

  .max-w-xl {
    max-width: var(--container-xl);
  }

  .min-w-0 {
    min-width: 0;
  }

  .flex-1 {
    flex: 1;
  }

  .shrink-0 {
    flex-shrink: 0;
  }

  .cursor-pointer {
    cursor: pointer;
  }

  .list-disc {
    list-style-type: disc;
  }

  .flex-col {
    flex-direction: column;
  }

  .flex-row {
    flex-direction: row;
  }

  .items-center {
    align-items: center;
  }

  .gap-1 {
    gap: var(--spacing);
  }

  .gap-1\\.5 {
    gap: calc(var(--spacing) * 1.5);
  }

  .gap-2 {
    gap: calc(var(--spacing) * 2);
  }

  .gap-3 {
    gap: calc(var(--spacing) * 3);
  }

  .gap-6 {
    gap: calc(var(--spacing) * 6);
  }

  .gap-7 {
    gap: calc(var(--spacing) * 7);
  }

  .rounded-md {
    border-radius: calc(var(--radius) - 2px);
  }

  .border {
    border-style: var(--tw-border-style);
    border-width: 1px;
  }

  .border-none {
    --tw-border-style: none;
    border-style: none;
  }

  .border-border {
    border-color: var(--border);
  }

  .bg-background {
    background-color: var(--background);
  }

  .bg-border {
    background-color: var(--border);
  }

  .bg-input {
    background-color: var(--input);
  }

  .bg-popover {
    background-color: var(--popover);
  }

  .bg-transparent {
    background-color: #0000;
  }

  .p-0 {
    padding: 0;
  }

  .p-6 {
    padding: calc(var(--spacing) * 6);
  }

  .px-2 {
    padding-inline: calc(var(--spacing) * 2);
  }

  .px-3 {
    padding-inline: calc(var(--spacing) * 3);
  }

  .py-1 {
    padding-block: var(--spacing);
  }

  .py-2\\.5 {
    padding-block: calc(var(--spacing) * 2.5);
  }

  .pr-3 {
    padding-right: calc(var(--spacing) * 3);
  }

  .font-sans {
    font-family: var(--font-roobert);
  }

  .text-base {
    font-size: 1rem;
    line-height: var(--tw-leading, calc(1.5 / 1));
  }

  .text-sm {
    font-size: .875rem;
    line-height: var(--tw-leading, calc(1.25 / .875));
  }

  .text-xs {
    font-size: .8125rem;
    line-height: var(--tw-leading, calc(1 / .8125));
  }

  .leading-none {
    --tw-leading: 1;
    line-height: 1;
  }

  .leading-normal {
    --tw-leading: var(--leading-normal);
    line-height: var(--leading-normal);
  }

  .leading-snug {
    --tw-leading: var(--leading-snug);
    line-height: var(--leading-snug);
  }

  .font-medium {
    --tw-font-weight: var(--font-weight-medium);
    font-weight: var(--font-weight-medium);
  }

  .font-normal {
    --tw-font-weight: var(--font-weight-normal);
    font-weight: var(--font-weight-normal);
  }

  .text-destructive {
    color: var(--destructive);
  }

  .text-foreground {
    color: var(--foreground);
  }

  .text-muted-foreground, .text-muted-foreground\\/70 {
    color: var(--muted-foreground);
  }

  @supports (color: color-mix(in lab, red, red)) {
    .text-muted-foreground\\/70 {
      color: color-mix(in oklab, var(--muted-foreground) 70%, transparent);
    }
  }

  .text-secondary-foreground {
    color: var(--secondary-foreground);
  }

  .italic {
    font-style: italic;
  }

  .accent-kortix-blue {
    accent-color: var(--kortix-blue);
  }

  .outline {
    outline-style: var(--tw-outline-style);
    outline-width: 1px;
  }

  .transition-\\[color\\] {
    transition-property: color;
    transition-timing-function: var(--tw-ease, var(--default-transition-timing-function));
    transition-duration: var(--tw-duration, var(--default-transition-duration));
  }

  .outline-none {
    --tw-outline-style: none;
    outline-style: none;
  }

  .select-none {
    -webkit-user-select: none;
    user-select: none;
  }

  .group-has-\\[\\[data-orientation\\=horizontal\\]\\]\\/field\\:text-balance:is(:where(.group\\/field):has([data-orientation="horizontal"]) *) {
    text-wrap: balance;
  }

  .group-data-\\[disabled\\=true\\]\\:pointer-events-none:is(:where(.group)[data-disabled="true"] *) {
    pointer-events: none;
  }

  .group-data-\\[disabled\\=true\\]\\:opacity-50:is(:where(.group)[data-disabled="true"] *), .group-data-\\[disabled\\=true\\]\\/field\\:opacity-50:is(:where(.group\\/field)[data-disabled="true"] *) {
    opacity: .5;
  }

  .group-data-\\[variant\\=outline\\]\\/field-group\\:-mb-2:is(:where(.group\\/field-group)[data-variant="outline"] *) {
    margin-bottom: calc(var(--spacing) * -2);
  }

  .peer-disabled\\:cursor-not-allowed:is(:where(.peer):disabled ~ *) {
    cursor: not-allowed;
  }

  .peer-disabled\\:opacity-50:is(:where(.peer):disabled ~ *) {
    opacity: .5;
  }

  .selection\\:bg-primary ::selection {
    background-color: var(--primary);
  }

  .selection\\:bg-primary::selection {
    background-color: var(--primary);
  }

  .selection\\:text-primary-foreground ::selection {
    color: var(--primary-foreground);
  }

  .selection\\:text-primary-foreground::selection {
    color: var(--primary-foreground);
  }

  .file\\:me-3::file-selector-button {
    margin-inline-end: calc(var(--spacing) * 3);
  }

  .file\\:inline-flex::file-selector-button {
    display: inline-flex;
  }

  .file\\:h-7::file-selector-button {
    height: calc(var(--spacing) * 7);
  }

  .file\\:h-full::file-selector-button {
    height: 100%;
  }

  .file\\:border-0::file-selector-button {
    border-style: var(--tw-border-style);
    border-width: 0;
  }

  .file\\:border-r::file-selector-button {
    border-right-style: var(--tw-border-style);
    border-right-width: 1px;
  }

  .file\\:border-solid::file-selector-button {
    --tw-border-style: solid;
    border-style: solid;
  }

  .file\\:border-input::file-selector-button {
    border-color: var(--input);
  }

  .file\\:bg-transparent::file-selector-button {
    background-color: #0000;
  }

  .file\\:px-3::file-selector-button {
    padding-inline: calc(var(--spacing) * 3);
  }

  .file\\:text-sm::file-selector-button {
    font-size: .875rem;
    line-height: var(--tw-leading, calc(1.25 / .875));
  }

  .file\\:font-medium::file-selector-button {
    --tw-font-weight: var(--font-weight-medium);
    font-weight: var(--font-weight-medium);
  }

  .file\\:text-foreground::file-selector-button {
    color: var(--foreground);
  }

  .file\\:not-italic::file-selector-button {
    font-style: normal;
  }

  .placeholder\\:text-muted-foreground::placeholder {
    color: var(--muted-foreground);
  }

  .last\\:mt-0:last-child {
    margin-top: 0;
  }

  .focus\\:border:focus {
    border-style: var(--tw-border-style);
    border-width: 1px;
  }

  .focus\\:border-kortix-blue:focus {
    border-color: var(--kortix-blue);
  }

  .focus\\:outline-none:focus {
    --tw-outline-style: none;
    outline-style: none;
  }

  .disabled\\:pointer-events-none:disabled {
    pointer-events: none;
  }

  .disabled\\:cursor-not-allowed:disabled {
    cursor: not-allowed;
  }

  .disabled\\:opacity-50:disabled {
    opacity: .5;
  }

  .has-data-\\[state\\=checked\\]\\:border-primary:has([data-state="checked"]) {
    border-color: var(--primary);
  }

  .has-data-\\[state\\=checked\\]\\:bg-primary\\/5:has([data-state="checked"]) {
    background-color: var(--primary);
  }

  @supports (color: color-mix(in lab, red, red)) {
    .has-data-\\[state\\=checked\\]\\:bg-primary\\/5:has([data-state="checked"]) {
      background-color: color-mix(in oklab, var(--primary) 5%, transparent);
    }
  }

  .has-\\[\\>\\[data-slot\\=checkbox-group\\]\\]\\:gap-3:has( > [data-slot="checkbox-group"]) {
    gap: calc(var(--spacing) * 3);
  }

  .has-\\[\\>\\[data-slot\\=field-content\\]\\]\\:items-start:has( > [data-slot="field-content"]) {
    align-items: flex-start;
  }

  .has-\\[\\>\\[data-slot\\=field\\]\\]\\:w-full:has( > [data-slot="field"]) {
    width: 100%;
  }

  .has-\\[\\>\\[data-slot\\=field\\]\\]\\:flex-col:has( > [data-slot="field"]) {
    flex-direction: column;
  }

  .has-\\[\\>\\[data-slot\\=field\\]\\]\\:rounded-md:has( > [data-slot="field"]) {
    border-radius: calc(var(--radius) - 2px);
  }

  .has-\\[\\>\\[data-slot\\=field\\]\\]\\:border:has( > [data-slot="field"]) {
    border-style: var(--tw-border-style);
    border-width: 1px;
  }

  .has-\\[\\>\\[data-slot\\=radio-group\\]\\]\\:gap-3:has( > [data-slot="radio-group"]) {
    gap: calc(var(--spacing) * 3);
  }

  .aria-invalid\\:border-destructive[aria-invalid="true"] {
    border-color: var(--destructive);
  }

  .aria-invalid\\:ring-destructive\\/20[aria-invalid="true"] {
    --tw-ring-color: var(--destructive);
  }

  @supports (color: color-mix(in lab, red, red)) {
    .aria-invalid\\:ring-destructive\\/20[aria-invalid="true"] {
      --tw-ring-color: color-mix(in oklab, var(--destructive) 20%, transparent);
    }
  }

  .data-\\[invalid\\=true\\]\\:text-destructive[data-invalid="true"] {
    color: var(--destructive);
  }

  .data-\\[orientation\\=horizontal\\]\\:h-px[data-orientation="horizontal"] {
    height: 1px;
  }

  .data-\\[orientation\\=horizontal\\]\\:w-full[data-orientation="horizontal"] {
    width: 100%;
  }

  .data-\\[orientation\\=vertical\\]\\:h-full[data-orientation="vertical"] {
    height: 100%;
  }

  .data-\\[orientation\\=vertical\\]\\:w-px[data-orientation="vertical"] {
    width: 1px;
  }

  .data-\\[slot\\=checkbox-group\\]\\:gap-3[data-slot="checkbox-group"] {
    gap: calc(var(--spacing) * 3);
  }

  .data-\\[variant\\=label\\]\\:text-sm[data-variant="label"] {
    font-size: .875rem;
    line-height: var(--tw-leading, calc(1.25 / .875));
  }

  .data-\\[variant\\=legend\\]\\:text-base[data-variant="legend"] {
    font-size: 1rem;
    line-height: var(--tw-leading, calc(1.5 / 1));
  }

  .nth-last-2\\:-mt-1:nth-last-child(2) {
    margin-top: calc(var(--spacing) * -1);
  }

  @media (prefers-reduced-motion: no-preference) {
    .aria-invalid\\:motion-safe\\:animate-shake[aria-invalid="true"] {
      animation: shake .4s var(--ease-in-out) both;
    }
  }

  @container field-group (min-width: 28rem) {
    .\\@md\\/field-group\\:flex-row {
      flex-direction: row;
    }

    .\\@md\\/field-group\\:items-center {
      align-items: center;
    }

    .\\@md\\/field-group\\:has-\\[\\>\\[data-slot\\=field-content\\]\\]\\:items-start:has( > [data-slot="field-content"]) {
      align-items: flex-start;
    }
  }

  .dark\\:has-data-\\[state\\=checked\\]\\:bg-primary\\/10:where(.dark, .dark *):has([data-state="checked"]) {
    background-color: var(--primary);
  }

  @supports (color: color-mix(in lab, red, red)) {
    .dark\\:has-data-\\[state\\=checked\\]\\:bg-primary\\/10:where(.dark, .dark *):has([data-state="checked"]) {
      background-color: color-mix(in oklab, var(--primary) 10%, transparent);
    }
  }

  .dark\\:aria-invalid\\:ring-destructive\\/40:where(.dark, .dark *)[aria-invalid="true"] {
    --tw-ring-color: var(--destructive);
  }

  @supports (color: color-mix(in lab, red, red)) {
    .dark\\:aria-invalid\\:ring-destructive\\/40:where(.dark, .dark *)[aria-invalid="true"] {
      --tw-ring-color: color-mix(in oklab, var(--destructive) 40%, transparent);
    }
  }

  .\\[\\&\\:\\:-webkit-search-cancel-button\\]\\:appearance-none::-webkit-search-cancel-button {
    appearance: none;
  }

  .\\[\\&\\:\\:-webkit-search-decoration\\]\\:appearance-none::-webkit-search-decoration {
    appearance: none;
  }

  .\\[\\&\\:\\:-webkit-search-results-button\\]\\:appearance-none::-webkit-search-results-button {
    appearance: none;
  }

  .\\[\\&\\:\\:-webkit-search-results-decoration\\]\\:appearance-none::-webkit-search-results-decoration {
    appearance: none;
  }

  .\\[\\&\\>\\*\\]\\:w-full > * {
    width: 100%;
  }

  .\\[\\&\\>\\*\\]\\:data-\\[slot\\=field\\]\\:p-4 > [data-slot="field"] {
    padding: calc(var(--spacing) * 4);
  }

  @container field-group (min-width: 28rem) {
    .\\@md\\/field-group\\:\\[\\&\\>\\*\\]\\:w-auto > * {
      width: auto;
    }
  }

  .\\[\\&\\>\\.sr-only\\]\\:w-auto > .sr-only {
    width: auto;
  }

  .\\[\\&\\>\\[data-slot\\=field-group\\]\\]\\:gap-4 > [data-slot="field-group"] {
    gap: calc(var(--spacing) * 4);
  }

  .\\[\\&\\>\\[data-slot\\=field-label\\]\\]\\:flex-auto > [data-slot="field-label"] {
    flex: auto;
  }

  @container field-group (min-width: 28rem) {
    .\\@md\\/field-group\\:\\[\\&\\>\\[data-slot\\=field-label\\]\\]\\:flex-auto > [data-slot="field-label"] {
      flex: auto;
    }
  }

  .has-\\[\\>\\[data-slot\\=field-content\\]\\]\\:\\[\\&\\>\\[role\\=checkbox\\]\\,\\[role\\=radio\\]\\]\\:mt-px:has( > [data-slot="field-content"]) > [role="checkbox"], .has-\\[\\>\\[data-slot\\=field-content\\]\\]\\:\\[\\&\\>\\[role\\=checkbox\\]\\,\\[role\\=radio\\]\\]\\:mt-px:has( > [data-slot="field-content"]) [role="radio"] {
    margin-top: 1px;
  }

  @container field-group (min-width: 28rem) {
    .\\@md\\/field-group\\:has-\\[\\>\\[data-slot\\=field-content\\]\\]\\:\\[\\&\\>\\[role\\=checkbox\\]\\,\\[role\\=radio\\]\\]\\:mt-px:has( > [data-slot="field-content"]) > [role="checkbox"], .\\@md\\/field-group\\:has-\\[\\>\\[data-slot\\=field-content\\]\\]\\:\\[\\&\\>\\[role\\=checkbox\\]\\,\\[role\\=radio\\]\\]\\:mt-px:has( > [data-slot="field-content"]) [role="radio"] {
      margin-top: 1px;
    }
  }

  .\\[\\&\\>a\\]\\:underline > a {
    text-decoration-line: underline;
  }

  .\\[\\&\\>a\\]\\:underline-offset-4 > a {
    text-underline-offset: 4px;
  }

  .\\[\\&\\>a\\:hover\\]\\:text-primary > a:hover {
    color: var(--primary);
  }

  [data-variant="legend"] + .\\[\\[data-variant\\=legend\\]\\+\\&\\]\\:-mt-1\\.5 {
    margin-top: calc(var(--spacing) * -1.5);
  }


:root {
  --background: oklch(100% 0 0);
  --pane: oklch(100% 0 0);
  --foreground: oklch(0% 0 0);
  --foreground-strong: var(--foreground);
  --foreground-weak: var(--muted-foreground);
  --card: oklch(96.72% 0 0);
  --card-foreground: oklch(0% 0 0);
  --popover: oklch(100% 0 0);
  --popover-foreground: oklch(0% 0 0);
  --primary: oklch(0% 0 0);
  --primary-foreground: oklch(100% 0 0);
  --secondary: oklch(94.31% 0 0);
  --secondary-foreground: oklch(0% 0 0);
  --muted: oklch(94.31% 0 0);
  --muted-foreground: oklch(51.03% 0 0);
  --accent: oklch(96.72% 0 0);
  --accent-foreground: oklch(0% 0 0);
  --destructive: oklch(58.3% .2387 28.4765);
  --destructive-foreground: oklch(98.51% 0 0);
  --border: oklch(91.28% 0 0);
  --input: oklch(94.31% 0 0);
  --ring: oklch(66.9% .1837 248.807);
  --hover: oklch(0% 0 0 / .045);
  --active: oklch(0% 0 0 / .075);
  --focus-ring: var(--ring);
  --chart-1: oklch(87.81% .1688 91.8567);
  --chart-2: oklch(77.24% .1728 65.367);
  --chart-3: oklch(66.71% .1685 53.3814);
  --chart-4: oklch(55.7% .1583 45.3594);
  --chart-5: oklch(47.47% .1358 44.9806);
  --sidebar: oklch(96.72% 0 0);
  --sidebar-foreground: oklch(0% 0 0);
  --sidebar-primary: oklch(66.9% .1837 248.807);
  --sidebar-primary-foreground: oklch(100% 0 0);
  --sidebar-accent: oklch(94.31% 0 0);
  --sidebar-accent-foreground: oklch(0% 0 0);
  --sidebar-border: oklch(91.28% 0 0);
  --sidebar-ring: oklch(66.9% .1837 248.807);
  --radius: .625rem;
  --tracking-normal: 0em;
  --spacing: .23rem;
  --kortix-base: var(--color-ring);
  --kortix-blue: oklch(65.2% .177 252.624);
  --kortix-yellow: oklch(73.2% .15 90.688);
  --kortix-orange: oklch(69.1% .142 71.784);
  --kortix-green: oklch(58.1% .165 146.619);
  --kortix-purple: oklch(67.5% .131 306.212);
  --kortix-red: oklch(64.8% .202 24.745);
  --duration-fast: .1s;
  --duration-normal: .15s;
  --duration-moderate: .2s;
  --duration-slow: .3s;
  --duration-slower: .5s;
  --ease-default: cubic-bezier(.2, 0, 0, 1);
  --ease-in: cubic-bezier(.4, 0, 1, 1);
  --ease-out: cubic-bezier(0, 0, .2, 1);
  --ease-in-out: cubic-bezier(.4, 0, .2, 1);
}

.dark {
  --background: oklch(17% 0 0);
  --pane: oklch(15.43% 0 0);
  --foreground: oklch(100% 0 0);
  --foreground-strong: var(--foreground);
  --foreground-weak: var(--muted-foreground);
  --card: oklch(19.13% 0 0);
  --card-foreground: oklch(100% 0 0);
  --popover: oklch(19.13% 0 0);
  --popover-foreground: oklch(100% 0 0);
  --primary: oklch(100% 0 0);
  --primary-foreground: oklch(13.98% 0 0);
  --secondary: oklch(22.64% 0 0);
  --secondary-foreground: oklch(100% 0 0);
  --muted: oklch(22.64% 0 0);
  --muted-foreground: oklch(68.3% 0 0);
  --accent: oklch(19.13% 0 0);
  --accent-foreground: oklch(100% 0 0);
  --destructive: oklch(70.22% .1892 22.2279);
  --destructive-foreground: oklch(98.51% 0 0);
  --border: oklch(26.86% 0 0);
  --input: oklch(22.64% 0 0);
  --ring: oklch(66.9% .1837 248.807);
  --hover: oklch(100% 0 0 / .06);
  --active: oklch(100% 0 0 / .1);
  --focus-ring: var(--ring);
  --chart-1: oklch(87.81% .1688 91.8567);
  --chart-2: oklch(77.24% .1728 65.367);
  --chart-3: oklch(66.71% .1685 53.3814);
  --chart-4: oklch(55.7% .1583 45.3594);
  --chart-5: oklch(47.47% .1358 44.9806);
  --sidebar: oklch(19.13% 0 0);
  --sidebar-foreground: oklch(100% 0 0);
  --sidebar-primary: oklch(66.9% .1837 248.807);
  --sidebar-primary-foreground: oklch(100% 0 0);
  --sidebar-accent: oklch(22.64% 0 0);
  --sidebar-accent-foreground: oklch(100% 0 0);
  --sidebar-border: oklch(21.78% 0 0);
  --sidebar-ring: oklch(66.9% .1837 248.807);
  --radius: .625rem;
  --kortix-base: var(--color-ring);
  --kortix-blue: oklch(65.2% .177 252.624);
  --kortix-yellow: oklch(73.2% .15 90.688);
  --kortix-orange: oklch(69.1% .142 71.784);
  --kortix-green: oklch(58.1% .165 146.619);
  --kortix-purple: oklch(67.5% .131 306.212);
  --kortix-red: oklch(64.8% .202 24.745);
}

@keyframes spinner-orbit {
  to {
    transform: rotate(360deg);
  }
}

@keyframes spinner-spin {
  to {
    transform: rotate(360deg);
  }
}

@keyframes spinner-dash {
  0% {
    stroke-dashoffset: 58px;
    transform: rotate(0);
  }

  50% {
    stroke-dashoffset: 14px;
    transform: rotate(180deg);
  }

  100% {
    stroke-dashoffset: 58px;
    transform: rotate(360deg);
  }
}

.animate-spinner-orbit {
  transform-origin: center;
  animation: 1.4s linear infinite spinner-orbit;
}

.animate-spinner-spin {
  transform-origin: center;
  animation: 1s linear infinite spinner-spin;
}

.animate-spinner-dash {
  transform-origin: center;
  transform-box: fill-box;
  stroke-dasharray: 62.83;
  animation: 1.4s cubic-bezier(.77, 0, .175, 1) infinite spinner-dash;
}

@keyframes spinner-spokes {
  to {
    transform: rotate(360deg);
  }
}

.animate-spinner-spokes {
  transform-origin: center;
  animation: .8s steps(8, end) infinite spinner-spokes;
}

@media (prefers-reduced-motion: reduce) {
  .animate-spinner-orbit, .animate-spinner-spin {
    animation: 1.4s linear infinite spinner-orbit;
  }

  .animate-spinner-dash {
    stroke-dashoffset: 34px;
    animation: none;
    transform: none;
  }

  .animate-spinner-spokes {
    animation: 1.4s linear infinite spinner-spokes;
  }
}

@property --tw-border-style {
  syntax: "*";
  inherits: false;
  initial-value: solid;
}

@property --tw-leading {
  syntax: "*";
  inherits: false
}

@property --tw-font-weight {
  syntax: "*";
  inherits: false
}

@property --tw-outline-style {
  syntax: "*";
  inherits: false;
  initial-value: solid;
}

@keyframes shake {
  0%, 100% {
    transform: translateX(0);
  }

  10% {
    transform: translateX(-6px);
  }

  30% {
    transform: translateX(5px);
  }

  50% {
    transform: translateX(-3px);
  }

  70% {
    transform: translateX(2px);
  }

  90% {
    transform: translateX(-1px);
  }
}
`;
