/* AUTO-GENERATED by scripts/gen-preview-css.mjs -- do not edit by hand.
 * Real Tailwind v4 output for Alert's own classes, compiled against
 * tokens/kortix-tokens.css. Inlined because the preview sandbox runs
 * Tailwind v3 and cannot resolve Suna's v4 @theme tokens. */
export const PREVIEW_CSS = `/*! tailwindcss v4.3.3 | MIT License | https://tailwindcss.com */

  @supports (((-webkit-hyphens: none)) and (not (margin-trim: inline))) or ((-moz-orient: inline) and (not (color: rgb(from red r g b)))) {
    *, :before, :after, ::backdrop {
      --tw-space-y-reverse: 0;
      --tw-border-style: solid;
      --tw-leading: initial;
      --tw-font-weight: initial;
      --tw-tracking: initial;
      --tw-outline-style: solid;
      --tw-duration: initial;
      --tw-translate-x: 0;
      --tw-translate-y: 0;
      --tw-translate-z: 0;
      --tw-shadow: 0 0 #0000;
      --tw-shadow-color: initial;
      --tw-shadow-alpha: 100%;
      --tw-inset-shadow: 0 0 #0000;
      --tw-inset-shadow-color: initial;
      --tw-inset-shadow-alpha: 100%;
      --tw-ring-color: initial;
      --tw-ring-shadow: 0 0 #0000;
      --tw-inset-ring-color: initial;
      --tw-inset-ring-shadow: 0 0 #0000;
      --tw-ring-inset: initial;
      --tw-ring-offset-width: 0px;
      --tw-ring-offset-color: #fff;
      --tw-ring-offset-shadow: 0 0 #0000;
    }
  }



  :root, :host {
    --spacing: .25rem;
    --font-weight-normal: 400;
    --font-weight-medium: 500;
    --tracking-tight: -.025em;
    --leading-snug: 1.375;
    --leading-normal: 1.5;
    --leading-relaxed: 1.625;
    --default-transition-duration: .15s;
    --default-transition-timing-function: cubic-bezier(.4, 0, .2, 1);
    --default-font-family: var(--font-roobert);
    --default-mono-font-family: var(--font-roobert-mono);
    --color-ring: var(--ring);
  }



  *, :after, :before, ::backdrop {
    box-sizing: border-box;
    border: 0 solid;
    margin: 0;
    padding: 0;
  }

  ::file-selector-button {
    box-sizing: border-box;
    border: 0 solid;
    margin: 0;
    padding: 0;
  }

  html, :host {
    -webkit-text-size-adjust: 100%;
    tab-size: 4;
    line-height: 1.5;
    font-family: var(--default-font-family, -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, "Helvetica Neue", "Noto Sans", Arial, sans-serif, "Apple Color Emoji", "Segoe UI Emoji", "Segoe UI Symbol", "Noto Color Emoji");
    font-feature-settings: var(--default-font-feature-settings, normal);
    font-variation-settings: var(--default-font-variation-settings, normal);
    -webkit-tap-highlight-color: transparent;
  }

  hr {
    height: 0;
    color: inherit;
    border-top-width: 1px;
  }

  abbr:where([title]) {
    -webkit-text-decoration: underline dotted;
    text-decoration: underline dotted;
  }

  h1, h2, h3, h4, h5, h6 {
    font-size: inherit;
    font-weight: inherit;
  }

  a {
    color: inherit;
    -webkit-text-decoration: inherit;
    -webkit-text-decoration: inherit;
    -webkit-text-decoration: inherit;
    text-decoration: inherit;
  }

  b, strong {
    font-weight: bolder;
  }

  code, kbd, samp, pre {
    font-family: var(--default-mono-font-family, ui-monospace, SFMono-Regular, Menlo, Monaco, Consolas, "Liberation Mono", "Courier New", monospace);
    font-feature-settings: var(--default-mono-font-feature-settings, normal);
    font-variation-settings: var(--default-mono-font-variation-settings, normal);
    font-size: 1em;
  }

  small {
    font-size: 80%;
  }

  sub, sup {
    vertical-align: baseline;
    font-size: 75%;
    line-height: 0;
    position: relative;
  }

  sub {
    bottom: -.25em;
  }

  sup {
    top: -.5em;
  }

  table {
    text-indent: 0;
    border-color: inherit;
    border-collapse: collapse;
  }

  :-moz-focusring:where(:not(iframe)) {
    outline: auto;
  }

  progress {
    vertical-align: baseline;
  }

  summary {
    display: list-item;
  }

  ol, ul, menu {
    list-style: none;
  }

  img, svg, video, canvas, audio, iframe, embed, object {
    vertical-align: middle;
    display: block;
  }

  img, video {
    max-width: 100%;
    height: auto;
  }

  button, input, select, optgroup, textarea {
    font: inherit;
    font-feature-settings: inherit;
    font-variation-settings: inherit;
    letter-spacing: inherit;
    color: inherit;
    opacity: 1;
    background-color: #0000;
    border-radius: 0;
  }

  ::file-selector-button {
    font: inherit;
    font-feature-settings: inherit;
    font-variation-settings: inherit;
    letter-spacing: inherit;
    color: inherit;
    opacity: 1;
    background-color: #0000;
    border-radius: 0;
  }

  :where(select:is([multiple], [size])) optgroup {
    font-weight: bolder;
  }

  :where(select:is([multiple], [size])) optgroup option {
    padding-inline-start: 20px;
  }

  ::file-selector-button {
    margin-inline-end: 4px;
  }

  ::placeholder {
    opacity: 1;
  }

  @supports (not ((-webkit-appearance: -apple-pay-button))) or (contain-intrinsic-size: 1px) {
    ::placeholder {
      color: currentColor;
    }

    @supports (color: color-mix(in lab, red, red)) {
      ::placeholder {
        color: color-mix(in oklab, currentcolor 50%, transparent);
      }
    }
  }

  textarea {
    resize: vertical;
  }

  ::-webkit-search-decoration {
    -webkit-appearance: none;
  }

  ::-webkit-date-and-time-value {
    min-height: 1lh;
    text-align: inherit;
  }

  ::-webkit-datetime-edit {
    display: inline-flex;
  }

  ::-webkit-datetime-edit-fields-wrapper {
    padding: 0;
  }

  ::-webkit-datetime-edit {
    padding-block: 0;
  }

  ::-webkit-datetime-edit-year-field {
    padding-block: 0;
  }

  ::-webkit-datetime-edit-month-field {
    padding-block: 0;
  }

  ::-webkit-datetime-edit-day-field {
    padding-block: 0;
  }

  ::-webkit-datetime-edit-hour-field {
    padding-block: 0;
  }

  ::-webkit-datetime-edit-minute-field {
    padding-block: 0;
  }

  ::-webkit-datetime-edit-second-field {
    padding-block: 0;
  }

  ::-webkit-datetime-edit-millisecond-field {
    padding-block: 0;
  }

  ::-webkit-datetime-edit-meridiem-field {
    padding-block: 0;
  }

  ::-webkit-calendar-picker-indicator {
    line-height: 1;
  }

  :-moz-ui-invalid {
    box-shadow: none;
  }

  button, input:where([type="button"], [type="reset"], [type="submit"]) {
    appearance: button;
  }

  ::file-selector-button {
    appearance: button;
  }

  ::-webkit-inner-spin-button {
    height: auto;
  }

  ::-webkit-outer-spin-button {
    height: auto;
  }

  [hidden]:where(:not([hidden="until-found"])) {
    display: none !important;
  }

  :root {
    color-scheme: light;
  }

  .dark {
    color-scheme: dark;
  }





  .my-0 {
    margin-block: 0;
  }

  .mt-0 {
    margin-top: 0;
  }

  .line-clamp-1 {
    -webkit-line-clamp: 1;
    -webkit-box-orient: vertical;
    display: -webkit-box;
    overflow: hidden;
  }

  .line-clamp-2 {
    -webkit-line-clamp: 2;
    -webkit-box-orient: vertical;
    display: -webkit-box;
    overflow: hidden;
  }

  .flex {
    display: flex;
  }

  .size-4 {
    width: calc(var(--spacing) * 4);
    height: calc(var(--spacing) * 4);
  }

  .size-8 {
    width: calc(var(--spacing) * 8);
    height: calc(var(--spacing) * 8);
  }

  .size-10 {
    width: calc(var(--spacing) * 10);
    height: calc(var(--spacing) * 10);
  }

  .h-7 {
    height: calc(var(--spacing) * 7);
  }

  .min-h-4 {
    min-height: calc(var(--spacing) * 4);
  }

  .w-fit {
    width: fit-content;
  }

  .w-full {
    width: 100%;
  }

  .flex-1 {
    flex: 1;
  }

  .shrink-0 {
    flex-shrink: 0;
  }

  .basis-full {
    flex-basis: 100%;
  }

  .flex-col {
    flex-direction: column;
  }

  .flex-wrap {
    flex-wrap: wrap;
  }

  .items-center {
    align-items: center;
  }

  .justify-between {
    justify-content: space-between;
  }

  .justify-center {
    justify-content: center;
  }

  .gap-1 {
    gap: var(--spacing);
  }

  .gap-2 {
    gap: calc(var(--spacing) * 2);
  }

  .gap-2\\.5 {
    gap: calc(var(--spacing) * 2.5);
  }

  .gap-4 {
    gap: calc(var(--spacing) * 4);
  }

  :where(.space-y-3 > :not(:last-child)) {
    --tw-space-y-reverse: 0;
    margin-block-start: calc(calc(var(--spacing) * 3) * var(--tw-space-y-reverse));
    margin-block-end: calc(calc(var(--spacing) * 3) * calc(1 - var(--tw-space-y-reverse)));
  }

  .self-start {
    align-self: flex-start;
  }

  .overflow-hidden {
    overflow: hidden;
  }

  .rounded-md {
    border-radius: calc(var(--radius) - 2px);
  }

  .rounded-sm {
    border-radius: calc(var(--radius) - 4px);
  }

  .border {
    border-style: var(--tw-border-style);
    border-width: 1px;
  }

  .border-border {
    border-color: var(--border);
  }

  .border-transparent {
    border-color: #0000;
  }

  .bg-background {
    background-color: var(--background);
  }

  .bg-border {
    background-color: var(--border);
  }

  .bg-foreground {
    background-color: var(--foreground);
  }

  .bg-kortix-orange\\/10 {
    background-color: var(--kortix-orange);
  }

  @supports (color: color-mix(in lab, red, red)) {
    .bg-kortix-orange\\/10 {
      background-color: color-mix(in oklab, var(--kortix-orange) 10%, transparent);
    }
  }

  .bg-muted, .bg-muted\\/50 {
    background-color: var(--muted);
  }

  @supports (color: color-mix(in lab, red, red)) {
    .bg-muted\\/50 {
      background-color: color-mix(in oklab, var(--muted) 50%, transparent);
    }
  }

  .bg-popover {
    background-color: var(--popover);
  }

  .bg-transparent {
    background-color: #0000;
  }

  .p-4 {
    padding: calc(var(--spacing) * 4);
  }

  .p-6 {
    padding: calc(var(--spacing) * 6);
  }

  .px-2\\.5 {
    padding-inline: calc(var(--spacing) * 2.5);
  }

  .px-4 {
    padding-inline: calc(var(--spacing) * 4);
  }

  .py-3 {
    padding-block: calc(var(--spacing) * 3);
  }

  .font-sans {
    font-family: var(--font-roobert);
  }

  .text-sm {
    font-size: .875rem;
    line-height: var(--tw-leading, calc(1.25 / .875));
  }

  .text-xs {
    font-size: .8125rem;
    line-height: var(--tw-leading, calc(1 / .8125));
  }

  .leading-normal {
    --tw-leading: var(--leading-normal);
    line-height: var(--leading-normal);
  }

  .leading-snug {
    --tw-leading: var(--leading-snug);
    line-height: var(--leading-snug);
  }

  .font-medium {
    --tw-font-weight: var(--font-weight-medium);
    font-weight: var(--font-weight-medium);
  }

  .font-normal {
    --tw-font-weight: var(--font-weight-normal);
    font-weight: var(--font-weight-normal);
  }

  .tracking-tight {
    --tw-tracking: var(--tracking-tight);
    letter-spacing: var(--tracking-tight);
  }

  .text-balance {
    text-wrap: balance;
  }

  .text-background {
    color: var(--background);
  }

  .text-destructive {
    color: var(--destructive);
  }

  .text-foreground {
    color: var(--foreground);
  }

  .text-kortix-orange {
    color: var(--kortix-orange);
  }

  .text-muted-foreground {
    color: var(--muted-foreground);
  }

  .outline {
    outline-style: var(--tw-outline-style);
    outline-width: 1px;
  }

  .transition-colors {
    transition-property: color, background-color, border-color, outline-color, text-decoration-color, fill, stroke, --tw-gradient-from, --tw-gradient-via, --tw-gradient-to;
    transition-timing-function: var(--tw-ease, var(--default-transition-timing-function));
    transition-duration: var(--tw-duration, var(--default-transition-duration));
  }

  .duration-100 {
    --tw-duration: .1s;
    transition-duration: .1s;
  }

  .outline-none {
    --tw-outline-style: none;
    outline-style: none;
  }

  .group-has-\\[\\[data-slot\\=item-description\\]\\]\\/item\\:translate-y-0\\.5:is(:where(.group\\/item):has([data-slot="item-description"]) *) {
    --tw-translate-y: calc(var(--spacing) * .5);
    translate: var(--tw-translate-x) var(--tw-translate-y);
  }

  .group-has-\\[\\[data-slot\\=item-description\\]\\]\\/item\\:self-start:is(:where(.group\\/item):has([data-slot="item-description"]) *) {
    align-self: flex-start;
  }

  @media (hover: hover) {
    .hover\\:bg-foreground\\/10:hover {
      background-color: var(--foreground);
    }

    @supports (color: color-mix(in lab, red, red)) {
      .hover\\:bg-foreground\\/10:hover {
        background-color: color-mix(in oklab, var(--foreground) 10%, transparent);
      }
    }

    .hover\\:bg-foreground\\/90:hover {
      background-color: var(--foreground);
    }

    @supports (color: color-mix(in lab, red, red)) {
      .hover\\:bg-foreground\\/90:hover {
        background-color: color-mix(in oklab, var(--foreground) 90%, transparent);
      }
    }

    .hover\\:text-foreground:hover {
      color: var(--foreground);
    }
  }

  .focus-visible\\:border-ring:focus-visible {
    border-color: var(--ring);
  }

  .focus-visible\\:ring-\\[3px\\]:focus-visible {
    --tw-ring-shadow: var(--tw-ring-inset, ) 0 0 0 calc(3px + var(--tw-ring-offset-width)) var(--tw-ring-color, currentcolor);
    box-shadow: var(--tw-inset-shadow), var(--tw-inset-ring-shadow), var(--tw-ring-offset-shadow), var(--tw-ring-shadow), var(--tw-shadow);
  }

  .focus-visible\\:ring-ring\\/50:focus-visible {
    --tw-ring-color: var(--ring);
  }

  @supports (color: color-mix(in lab, red, red)) {
    .focus-visible\\:ring-ring\\/50:focus-visible {
      --tw-ring-color: color-mix(in oklab, var(--ring) 50%, transparent);
    }
  }

  .data-\\[orientation\\=horizontal\\]\\:h-px[data-orientation="horizontal"] {
    height: 1px;
  }

  .data-\\[orientation\\=horizontal\\]\\:w-full[data-orientation="horizontal"] {
    width: 100%;
  }

  .data-\\[orientation\\=vertical\\]\\:h-full[data-orientation="vertical"] {
    height: 100%;
  }

  .data-\\[orientation\\=vertical\\]\\:w-px[data-orientation="vertical"] {
    width: 1px;
  }

  .\\[\\&_\\[data-slot\\=item-description\\]\\]\\:text-destructive\\/90 [data-slot="item-description"] {
    color: var(--destructive);
  }

  @supports (color: color-mix(in lab, red, red)) {
    .\\[\\&_\\[data-slot\\=item-description\\]\\]\\:text-destructive\\/90 [data-slot="item-description"] {
      color: color-mix(in oklab, var(--destructive) 90%, transparent);
    }
  }

  .\\[\\&_\\[data-slot\\=item-description\\]\\]\\:text-kortix-orange\\/90 [data-slot="item-description"] {
    color: var(--kortix-orange);
  }

  @supports (color: color-mix(in lab, red, red)) {
    .\\[\\&_\\[data-slot\\=item-description\\]\\]\\:text-kortix-orange\\/90 [data-slot="item-description"] {
      color: color-mix(in oklab, var(--kortix-orange) 90%, transparent);
    }
  }

  .\\[\\&_\\[data-slot\\=item-media\\]_svg\\]\\:text-current [data-slot="item-media"] svg {
    color: currentColor;
  }

  .\\[\\&_img\\]\\:size-full img {
    width: 100%;
    height: 100%;
  }

  .\\[\\&_img\\]\\:object-cover img {
    object-fit: cover;
  }

  .\\[\\&_p\\]\\:leading-relaxed p {
    --tw-leading: var(--leading-relaxed);
    line-height: var(--leading-relaxed);
  }

  .\\[\\&_svg\\]\\:pointer-events-none svg {
    pointer-events: none;
  }

  .\\[\\&_svg\\]\\:shrink-0 svg {
    flex-shrink: 0;
  }

  .\\[\\&_svg\\:not\\(\\[class\\*\\=\\'size-\\'\\]\\)\\]\\:size-4 svg:not([class*="size-"]) {
    width: calc(var(--spacing) * 4);
    height: calc(var(--spacing) * 4);
  }

  .\\[\\&\\+\\[data-slot\\=item-content\\]\\]\\:flex-none + [data-slot="item-content"] {
    flex: none;
  }

  .\\[a\\]\\:transition-colors:is(a) {
    transition-property: color, background-color, border-color, outline-color, text-decoration-color, fill, stroke, --tw-gradient-from, --tw-gradient-via, --tw-gradient-to;
    transition-timing-function: var(--tw-ease, var(--default-transition-timing-function));
    transition-duration: var(--tw-duration, var(--default-transition-duration));
  }

  @media (hover: hover) {
    .\\[a\\]\\:hover\\:bg-accent\\/50:is(a):hover {
      background-color: var(--accent);
    }

    @supports (color: color-mix(in lab, red, red)) {
      .\\[a\\]\\:hover\\:bg-accent\\/50:is(a):hover {
        background-color: color-mix(in oklab, var(--accent) 50%, transparent);
      }
    }
  }

  .\\[\\&\\>a\\]\\:underline > a {
    text-decoration-line: underline;
  }

  .\\[\\&\\>a\\]\\:underline-offset-4 > a {
    text-underline-offset: 4px;
  }

  .\\[\\&\\>a\\:hover\\]\\:text-primary > a:hover {
    color: var(--primary);
  }


:root {
  --background: oklch(100% 0 0);
  --pane: oklch(100% 0 0);
  --foreground: oklch(0% 0 0);
  --foreground-strong: var(--foreground);
  --foreground-weak: var(--muted-foreground);
  --card: oklch(96.72% 0 0);
  --card-foreground: oklch(0% 0 0);
  --popover: oklch(100% 0 0);
  --popover-foreground: oklch(0% 0 0);
  --primary: oklch(0% 0 0);
  --primary-foreground: oklch(100% 0 0);
  --secondary: oklch(94.31% 0 0);
  --secondary-foreground: oklch(0% 0 0);
  --muted: oklch(94.31% 0 0);
  --muted-foreground: oklch(51.03% 0 0);
  --accent: oklch(96.72% 0 0);
  --accent-foreground: oklch(0% 0 0);
  --destructive: oklch(58.3% .2387 28.4765);
  --destructive-foreground: oklch(98.51% 0 0);
  --border: oklch(91.28% 0 0);
  --input: oklch(94.31% 0 0);
  --ring: oklch(66.9% .1837 248.807);
  --hover: oklch(0% 0 0 / .045);
  --active: oklch(0% 0 0 / .075);
  --focus-ring: var(--ring);
  --chart-1: oklch(87.81% .1688 91.8567);
  --chart-2: oklch(77.24% .1728 65.367);
  --chart-3: oklch(66.71% .1685 53.3814);
  --chart-4: oklch(55.7% .1583 45.3594);
  --chart-5: oklch(47.47% .1358 44.9806);
  --sidebar: oklch(96.72% 0 0);
  --sidebar-foreground: oklch(0% 0 0);
  --sidebar-primary: oklch(66.9% .1837 248.807);
  --sidebar-primary-foreground: oklch(100% 0 0);
  --sidebar-accent: oklch(94.31% 0 0);
  --sidebar-accent-foreground: oklch(0% 0 0);
  --sidebar-border: oklch(91.28% 0 0);
  --sidebar-ring: oklch(66.9% .1837 248.807);
  --radius: .625rem;
  --tracking-normal: 0em;
  --spacing: .23rem;
  --kortix-base: var(--color-ring);
  --kortix-blue: oklch(65.2% .177 252.624);
  --kortix-yellow: oklch(73.2% .15 90.688);
  --kortix-orange: oklch(69.1% .142 71.784);
  --kortix-green: oklch(58.1% .165 146.619);
  --kortix-purple: oklch(67.5% .131 306.212);
  --kortix-red: oklch(64.8% .202 24.745);
  --duration-fast: .1s;
  --duration-normal: .15s;
  --duration-moderate: .2s;
  --duration-slow: .3s;
  --duration-slower: .5s;
  --ease-default: cubic-bezier(.2, 0, 0, 1);
  --ease-in: cubic-bezier(.4, 0, 1, 1);
  --ease-out: cubic-bezier(0, 0, .2, 1);
  --ease-in-out: cubic-bezier(.4, 0, .2, 1);
}

.dark {
  --background: oklch(17% 0 0);
  --pane: oklch(15.43% 0 0);
  --foreground: oklch(100% 0 0);
  --foreground-strong: var(--foreground);
  --foreground-weak: var(--muted-foreground);
  --card: oklch(19.13% 0 0);
  --card-foreground: oklch(100% 0 0);
  --popover: oklch(19.13% 0 0);
  --popover-foreground: oklch(100% 0 0);
  --primary: oklch(100% 0 0);
  --primary-foreground: oklch(13.98% 0 0);
  --secondary: oklch(22.64% 0 0);
  --secondary-foreground: oklch(100% 0 0);
  --muted: oklch(22.64% 0 0);
  --muted-foreground: oklch(68.3% 0 0);
  --accent: oklch(19.13% 0 0);
  --accent-foreground: oklch(100% 0 0);
  --destructive: oklch(70.22% .1892 22.2279);
  --destructive-foreground: oklch(98.51% 0 0);
  --border: oklch(26.86% 0 0);
  --input: oklch(22.64% 0 0);
  --ring: oklch(66.9% .1837 248.807);
  --hover: oklch(100% 0 0 / .06);
  --active: oklch(100% 0 0 / .1);
  --focus-ring: var(--ring);
  --chart-1: oklch(87.81% .1688 91.8567);
  --chart-2: oklch(77.24% .1728 65.367);
  --chart-3: oklch(66.71% .1685 53.3814);
  --chart-4: oklch(55.7% .1583 45.3594);
  --chart-5: oklch(47.47% .1358 44.9806);
  --sidebar: oklch(19.13% 0 0);
  --sidebar-foreground: oklch(100% 0 0);
  --sidebar-primary: oklch(66.9% .1837 248.807);
  --sidebar-primary-foreground: oklch(100% 0 0);
  --sidebar-accent: oklch(22.64% 0 0);
  --sidebar-accent-foreground: oklch(100% 0 0);
  --sidebar-border: oklch(21.78% 0 0);
  --sidebar-ring: oklch(66.9% .1837 248.807);
  --radius: .625rem;
  --kortix-base: var(--color-ring);
  --kortix-blue: oklch(65.2% .177 252.624);
  --kortix-yellow: oklch(73.2% .15 90.688);
  --kortix-orange: oklch(69.1% .142 71.784);
  --kortix-green: oklch(58.1% .165 146.619);
  --kortix-purple: oklch(67.5% .131 306.212);
  --kortix-red: oklch(64.8% .202 24.745);
}

@keyframes spinner-orbit {
  to {
    transform: rotate(360deg);
  }
}

@keyframes spinner-spin {
  to {
    transform: rotate(360deg);
  }
}

@keyframes spinner-dash {
  0% {
    stroke-dashoffset: 58px;
    transform: rotate(0);
  }

  50% {
    stroke-dashoffset: 14px;
    transform: rotate(180deg);
  }

  100% {
    stroke-dashoffset: 58px;
    transform: rotate(360deg);
  }
}

.animate-spinner-orbit {
  transform-origin: center;
  animation: 1.4s linear infinite spinner-orbit;
}

.animate-spinner-spin {
  transform-origin: center;
  animation: 1s linear infinite spinner-spin;
}

.animate-spinner-dash {
  transform-origin: center;
  transform-box: fill-box;
  stroke-dasharray: 62.83;
  animation: 1.4s cubic-bezier(.77, 0, .175, 1) infinite spinner-dash;
}

@keyframes spinner-spokes {
  to {
    transform: rotate(360deg);
  }
}

.animate-spinner-spokes {
  transform-origin: center;
  animation: .8s steps(8, end) infinite spinner-spokes;
}

@media (prefers-reduced-motion: reduce) {
  .animate-spinner-orbit, .animate-spinner-spin {
    animation: 1.4s linear infinite spinner-orbit;
  }

  .animate-spinner-dash {
    stroke-dashoffset: 34px;
    animation: none;
    transform: none;
  }

  .animate-spinner-spokes {
    animation: 1.4s linear infinite spinner-spokes;
  }
}

@property --tw-space-y-reverse {
  syntax: "*";
  inherits: false;
  initial-value: 0;
}

@property --tw-border-style {
  syntax: "*";
  inherits: false;
  initial-value: solid;
}

@property --tw-leading {
  syntax: "*";
  inherits: false
}

@property --tw-font-weight {
  syntax: "*";
  inherits: false
}

@property --tw-tracking {
  syntax: "*";
  inherits: false
}

@property --tw-outline-style {
  syntax: "*";
  inherits: false;
  initial-value: solid;
}

@property --tw-duration {
  syntax: "*";
  inherits: false
}

@property --tw-translate-x {
  syntax: "*";
  inherits: false;
  initial-value: 0;
}

@property --tw-translate-y {
  syntax: "*";
  inherits: false;
  initial-value: 0;
}

@property --tw-translate-z {
  syntax: "*";
  inherits: false;
  initial-value: 0;
}

@property --tw-shadow {
  syntax: "*";
  inherits: false;
  initial-value: 0 0 #0000;
}

@property --tw-shadow-color {
  syntax: "*";
  inherits: false
}

@property --tw-shadow-alpha {
  syntax: "<percentage>";
  inherits: false;
  initial-value: 100%;
}

@property --tw-inset-shadow {
  syntax: "*";
  inherits: false;
  initial-value: 0 0 #0000;
}

@property --tw-inset-shadow-color {
  syntax: "*";
  inherits: false
}

@property --tw-inset-shadow-alpha {
  syntax: "<percentage>";
  inherits: false;
  initial-value: 100%;
}

@property --tw-ring-color {
  syntax: "*";
  inherits: false
}

@property --tw-ring-shadow {
  syntax: "*";
  inherits: false;
  initial-value: 0 0 #0000;
}

@property --tw-inset-ring-color {
  syntax: "*";
  inherits: false
}

@property --tw-inset-ring-shadow {
  syntax: "*";
  inherits: false;
  initial-value: 0 0 #0000;
}

@property --tw-ring-inset {
  syntax: "*";
  inherits: false
}

@property --tw-ring-offset-width {
  syntax: "<length>";
  inherits: false;
  initial-value: 0;
}

@property --tw-ring-offset-color {
  syntax: "*";
  inherits: false;
  initial-value: #fff;
}

@property --tw-ring-offset-shadow {
  syntax: "*";
  inherits: false;
  initial-value: 0 0 #0000;
}
`;
