import { Manifest } from '../manifest/schema';
import { LockEntry } from '../lockfile/types';
import { readLockfile } from '../lockfile/lockfile';
import { resolveArtifact } from './pull';
import { ArtifactNotPulledError } from '../errors';

/**
 * Finds the already-pulled artifact `deliveryos wire-with-claude <id>`
 * needs -- its real lockfile entry (the source of the real, resolved
 * paths `buildWireContextMarkdown` renders) and its manifest. Extracted
 * from the CLI command itself so this resolution step is directly
 * unit-testable without spawning a `claude` process or invoking Commander,
 * same "engine holds the logic, the CLI command is a thin wrapper"
 * convention every other command in this codebase already follows.
 */
export function resolveWireTarget(
  cwd: string,
  id: string,
  remote: string | undefined,
): { manifest: Manifest; lockEntry: LockEntry } {
  const lockfile = readLockfile(cwd);
  const lockEntry = lockfile.entries.find((e) => e.id === id);
  if (!lockEntry) {
    throw new ArtifactNotPulledError(
      `"${id}" has no lockfile entry in this project -- pull it first with `
        + `"deliveryos pull ${id}" before wiring it in.`,
    );
  }

  const { manifest } = resolveArtifact(id, remote ?? lockEntry.remote);
  return { manifest, lockEntry };
}

/**
 * Renders the real, project-specific context a `deliveryos wire-with-claude`
 * session needs -- written to a FILE (`wireContextPath`, `.deliveryos/
 * wire-context-<id>.md`) rather than folded into the interactive session's
 * own starting message, because the starting message is passed via argv
 * under `shell: true` (see `launchInteractiveClaudeSession.ts`'s own doc
 * comment on why) -- interpolating this manifest's own `description` field
 * (artifact-author-controlled, not something DeliveryOS wrote) directly
 * into a shell-executed argv string would reopen exactly the Windows
 * command-injection risk `runClaudeSubprocess.ts`'s own doc comment
 * describes and deliberately avoids by using stdin instead of argv for its
 * own (different) subprocess shape. Here the mitigation is different but
 * the principle is the same: untrusted text only ever reaches Claude as
 * inert file content it reads via its own already-permissioned Read tool,
 * never as a live shell-interpolated command.
 *
 * Deliberately pure and synchronous -- no I/O, no subprocess -- so it's
 * directly unit-testable, same convention every other prompt/content
 * builder in this codebase already follows (`buildFixPrompt`,
 * `buildWiringMergePrompt`, `buildPlacementPrompt`).
 */
export function buildWireContextMarkdown(manifest: Manifest, lockEntry: LockEntry): string {
  const lines: string[] = [
    `# Wiring context for \`${manifest.id}\``,
    '',
    'This file was generated by `deliveryos wire-with-claude` from what was',
    'ACTUALLY pulled into this real project -- the paths below are the real,',
    'already-resolved locations (not a guess, not a hardcoded convention).',
    '',
    '## What this artifact is',
    '',
    manifest.description,
    '',
  ];

  if (lockEntry.installTarget) {
    lines.push(
      '## Where it landed',
      '',
      `\`${lockEntry.installTarget}\``,
      '',
    );
  }

  if (lockEntry.wiredFiles && lockEntry.wiredFiles.length > 0) {
    lines.push(
      '## Files already auto-wired into this project',
      '',
      ...lockEntry.wiredFiles.map((file) => `- \`${file}\``),
      '',
    );
  }

  lines.push(
    '## What to actually do',
    '',
    'Read the real files above (both the install location and the wired',
    'files) to see the real functions this artifact exports before writing',
    'anything. Connect this backend to the rest of this project for real --',
    'not a placeholder, not a hardcoded test value. Actually call the real',
    'functions now, in this same session -- don\'t stop at a documented',
    'seam (a comment describing what the real implementation would be,',
    'or an interface left unfilled for later). Confirm any route this',
    'protects is actually protected, run the project\'s real build, then',
    'walk the real flow yourself (not a simulated one) before calling it',
    'done.',
  );

  return lines.join('\n') + '\n';
}
