import { describe, it, expect, beforeEach, afterEach } from 'vitest';
import * as fs from 'fs';
import * as os from 'os';
import * as path from 'path';
import { computeChangedFiles, listFilesRecursive, listPayloadFiles } from '../../src/engine/push/diff';
import { PristineSnapshotMissingError } from '../../src/engine/errors';

let installTarget: string;
let pristineDir: string;

function write(root: string, relPath: string, content: string): void {
  const full = path.join(root, relPath);
  fs.mkdirSync(path.dirname(full), { recursive: true });
  fs.writeFileSync(full, content, 'utf-8');
}

beforeEach(() => {
  installTarget = fs.mkdtempSync(path.join(os.tmpdir(), 'deliveryos-diff-live-'));
  pristineDir = fs.mkdtempSync(path.join(os.tmpdir(), 'deliveryos-diff-pristine-'));
});

afterEach(() => {
  fs.rmSync(installTarget, { recursive: true, force: true });
  fs.rmSync(pristineDir, { recursive: true, force: true });
});

describe('computeChangedFiles', () => {
  it('reports no changes when live is byte-for-byte identical to pristine', () => {
    write(pristineDir, 'README.md', 'hello\n');
    write(installTarget, 'README.md', 'hello\n');

    expect(computeChangedFiles(installTarget, pristineDir)).toEqual([]);
  });

  it('detects an added file', () => {
    write(pristineDir, 'README.md', 'hello\n');
    write(installTarget, 'README.md', 'hello\n');
    write(installTarget, 'new.txt', 'new content\n');

    expect(computeChangedFiles(installTarget, pristineDir)).toEqual([
      { relPath: 'new.txt', status: 'added' },
    ]);
  });

  it('detects a modified file (content differs, same path)', () => {
    write(pristineDir, 'README.md', 'hello\n');
    write(installTarget, 'README.md', 'hello world\n');

    expect(computeChangedFiles(installTarget, pristineDir)).toEqual([
      { relPath: 'README.md', status: 'modified' },
    ]);
  });

  it('detects a deleted file', () => {
    write(pristineDir, 'README.md', 'hello\n');
    write(pristineDir, 'keep.txt', 'keep\n');
    write(installTarget, 'keep.txt', 'keep\n');

    expect(computeChangedFiles(installTarget, pristineDir)).toEqual([
      { relPath: 'README.md', status: 'deleted' },
    ]);
  });

  it('detects a mix of added/modified/deleted, sorted by relative path', () => {
    write(pristineDir, 'a.txt', 'a\n');
    write(pristineDir, 'b.txt', 'b\n');
    write(installTarget, 'a.txt', 'a changed\n');
    write(installTarget, 'c.txt', 'c\n');
    // b.txt is absent from installTarget -> deleted

    expect(computeChangedFiles(installTarget, pristineDir)).toEqual([
      { relPath: 'a.txt', status: 'modified' },
      { relPath: 'b.txt', status: 'deleted' },
      { relPath: 'c.txt', status: 'added' },
    ]);
  });

  it('detects changes in nested directories', () => {
    write(pristineDir, 'nested/keep.txt', 'keep\n');
    write(installTarget, 'nested/keep.txt', 'keep\n');
    write(installTarget, 'nested/deeper/new.txt', 'new\n');

    expect(computeChangedFiles(installTarget, pristineDir)).toEqual([
      { relPath: 'nested/deeper/new.txt', status: 'added' },
    ]);
  });

  it('ignores files matching the artifact\'s own .gitignore (e.g. __pycache__ generated by simply running a pulled Python tool)', () => {
    write(pristineDir, '.gitignore', '__pycache__/\n*.pyc\nnode_modules/\n');
    write(installTarget, '.gitignore', '__pycache__/\n*.pyc\nnode_modules/\n');
    write(pristineDir, 'cli/main.py', 'print("hi")\n');
    write(installTarget, 'cli/main.py', 'print("hi")\n');
    // Not a real edit -- generated by running the pulled tool after pull,
    // same as pip/npm generating cache dirs. Must not count as a change.
    write(installTarget, 'cli/__pycache__/main.cpython-313.pyc', '<bytecode>');
    write(installTarget, 'node_modules/.bin/some-tool', '<binary>');

    expect(computeChangedFiles(installTarget, pristineDir)).toEqual([]);
  });

  it('still detects a real edit alongside gitignored cache clutter', () => {
    write(pristineDir, '.gitignore', '__pycache__/\n');
    write(installTarget, '.gitignore', '__pycache__/\n');
    write(pristineDir, 'cli/main.py', 'print("hi")\n');
    write(installTarget, 'cli/main.py', 'print("hi there")\n'); // real edit
    write(installTarget, 'cli/__pycache__/main.cpython-313.pyc', '<bytecode>'); // noise

    expect(computeChangedFiles(installTarget, pristineDir)).toEqual([
      { relPath: 'cli/main.py', status: 'modified' },
    ]);
  });

  it('throws PristineSnapshotMissingError when the pristine dir does not exist at all', () => {
    fs.rmSync(pristineDir, { recursive: true, force: true });
    write(installTarget, 'a.txt', 'a\n');

    expect(() => computeChangedFiles(installTarget, pristineDir)).toThrow(
      PristineSnapshotMissingError,
    );
  });
});

describe('listFilesRecursive', () => {
  it('lists nested files as forward-slash relative paths', () => {
    write(installTarget, 'a.txt', 'a');
    write(installTarget, 'nested/b.txt', 'b');
    write(installTarget, 'nested/deeper/c.txt', 'c');

    expect(listFilesRecursive(installTarget).sort()).toEqual([
      'a.txt',
      'nested/b.txt',
      'nested/deeper/c.txt',
    ]);
  });

  it('returns an empty array for a nonexistent root', () => {
    expect(listFilesRecursive(path.join(installTarget, 'does-not-exist'))).toEqual([]);
  });

  it('never descends into a nested .git directory', () => {
    write(installTarget, 'a.txt', 'a');
    write(installTarget, '.git/objects/abc123', 'not a real git object, just noise');
    write(installTarget, '.git/HEAD', 'ref: refs/heads/main\n');

    expect(listFilesRecursive(installTarget).sort()).toEqual(['a.txt']);
  });
});

describe('listPayloadFiles', () => {
  it('excludes files matched by the payload\'s own .gitignore, on top of everything listFilesRecursive already excludes', () => {
    write(installTarget, '.gitignore', 'node_modules/\ndist/\n');
    write(installTarget, 'src/index.ts', 'export {}\n');
    write(installTarget, 'node_modules/some-dep/index.js', '// vendored\n');
    write(installTarget, 'dist/index.js', '// build output\n');
    write(installTarget, '.git/HEAD', 'ref: refs/heads/main\n');

    expect(listPayloadFiles(installTarget).sort()).toEqual(['.gitignore', 'src/index.ts']);
  });

  it('returns every file when there is no .gitignore at all', () => {
    write(installTarget, 'README.md', 'hello\n');
    write(installTarget, 'docs/guide.md', 'guide\n');

    expect(listPayloadFiles(installTarget).sort()).toEqual(['README.md', 'docs/guide.md']);
  });
});
